// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-admin
// Bundled from src/lib/mcp-admin/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-admin/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/tools/mcp-schema-get.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/errors.ts
var ERROR_CODES = [
  "VALIDATION_ERROR",
  "INVALID_SLUG",
  "SLUG_EXISTS",
  "TITLE_TOO_LONG",
  "AUTH_REQUIRED",
  "AUTH_EXPIRED",
  "AUTH_FAILED",
  "AUTH_DENIED",
  "GITHUB_UNAVAILABLE",
  "COMMIT_FAILED",
  "POST_NOT_FOUND",
  "CONFLICT",
  "INVALID_DATE",
  "TAG_NOT_FOUND",
  "LIMIT_EXCEEDED",
  "IMPORT_FAILED",
  "RATE_LIMITED",
  "INTERNAL_ERROR"
];
var OperationError = class extends Error {
  code;
  field;
  guidance;
  nextSteps;
  constructor(code, message, options = {}) {
    super(message);
    this.name = "OperationError";
    this.code = code;
    this.field = options.field;
    this.guidance = options.guidance;
    this.nextSteps = options.nextSteps;
  }
};
function toOperationError(error) {
  if (error instanceof OperationError) return error;
  const message = error instanceof Error ? error.message : String(error);
  if (/rate limit/i.test(message)) {
    return new OperationError("RATE_LIMITED", message, {
      guidance: "Wait for the GitHub rate-limit window to reset, then retry the same call."
    });
  }
  if (/authoriz|session|expired/i.test(message)) {
    return new OperationError("AUTH_EXPIRED", message, {
      guidance: "Call blog_auth_request to obtain a new session, then retry.",
      nextSteps: ["blog_auth_request", "blog_auth_verify"]
    });
  }
  if (/github/i.test(message)) {
    return new OperationError("GITHUB_UNAVAILABLE", message, {
      guidance: "GitHub rejected or failed the request. Retry once; if it persists, check repository access."
    });
  }
  return new OperationError("INTERNAL_ERROR", message, {
    guidance: "Retry the call. If the failure repeats, report the message verbatim."
  });
}

// src/lib/mcp-admin/env.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  const value = runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
  return value?.trim() || void 0;
}
function authEncryptionKey() {
  const key = runtimeEnv("MCP_AUTH_ENCRYPTION_KEY");
  if (!key) throw new Error("MCP authoring authentication is not configured.");
  return key;
}

// src/lib/mcp-admin/github-device-auth.ts
var GITHUB_CLIENT_ID = "Ov23li98oVkx9PDOvktP";
var ADMIN_LOGIN = "somritdasgupta";
var SESSION_TTL_MS = 60 * 60 * 1e3;
var APPROVAL_WINDOW_SECONDS = 180;
var MAX_LONG_POLL_MS = 2e4;
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var bytesToBase64Url = (bytes) => {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
};
var base64UrlToBytes = (value) => {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function encryptionKey() {
  const digest = await crypto.subtle.digest("SHA-256", encoder.encode(authEncryptionKey()));
  return crypto.subtle.importKey("raw", digest, "AES-GCM", false, ["encrypt", "decrypt"]);
}
async function seal(payload) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    await encryptionKey(),
    encoder.encode(JSON.stringify(payload))
  );
  return `${bytesToBase64Url(iv)}.${bytesToBase64Url(new Uint8Array(ciphertext))}`;
}
async function unseal(handle) {
  const [ivValue, ciphertextValue] = handle.split(".");
  if (!ivValue || !ciphertextValue) throw new Error("Invalid or expired authorization handle. Run blog_auth_request again.");
  try {
    const plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: base64UrlToBytes(ivValue) },
      await encryptionKey(),
      base64UrlToBytes(ciphertextValue)
    );
    return JSON.parse(decoder.decode(plaintext));
  } catch {
    throw new Error("Invalid or expired authorization handle. Run blog_auth_request again.");
  }
}
async function createAuthorization() {
  const response = await fetch("https://github.com/login/device/code", {
    method: "POST",
    headers: { Accept: "application/json", "Content-Type": "application/json" },
    body: JSON.stringify({ client_id: GITHUB_CLIENT_ID, scope: "repo" })
  });
  if (!response.ok) throw new Error(`GitHub authorization failed (${response.status}).`);
  const data = await response.json();
  const deviceCode = String(data.device_code ?? "");
  if (!deviceCode) throw new Error("GitHub did not return an authorization request.");
  const interval = Math.max(Number(data.interval ?? 5), 2);
  const expiresIn = Math.min(Number(data.expires_in ?? APPROVAL_WINDOW_SECONDS), APPROVAL_WINDOW_SECONDS);
  const expiresAt = Date.now() + expiresIn * 1e3;
  return {
    authorizationRequest: await seal({ purpose: "github-device", deviceCode, expiresAt, interval }),
    userCode: String(data.user_code ?? ""),
    verificationUri: String(data.verification_uri ?? "https://github.com/login/device"),
    expiresIn,
    pollUntil: new Date(expiresAt).toISOString(),
    interval
  };
}
async function exchangeDeviceCode(deviceCode) {
  const response = await fetch("https://github.com/login/oauth/access_token", {
    method: "POST",
    headers: { Accept: "application/json", "Content-Type": "application/json" },
    body: JSON.stringify({
      client_id: GITHUB_CLIENT_ID,
      device_code: deviceCode,
      grant_type: "urn:ietf:params:oauth:grant-type:device_code"
    })
  });
  const data = await response.json();
  if (data.access_token) return { state: "approved", token: String(data.access_token) };
  const error = String(data.error ?? "authorization_pending");
  const detail = String(data.error_description ?? error);
  if (error === "authorization_pending" || error === "slow_down") return { state: "pending" };
  if (error === "expired_token") return { state: "expired", detail: "The approval window closed before GitHub confirmed it." };
  return { state: "denied", detail };
}
async function githubUser(token) {
  const response = await fetch("https://api.github.com/user", {
    headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}` }
  });
  if (!response.ok) throw new Error(`GitHub identity check failed (${response.status}).`);
  return response.json();
}
var secondsLeft = (expiresAt) => Math.max(0, Math.round((expiresAt - Date.now()) / 1e3));
async function pollAuthorization(authorizationRequest, maxWaitMs = MAX_LONG_POLL_MS) {
  const request = await unseal(authorizationRequest);
  if (request.purpose !== "github-device" || !request.deviceCode) {
    throw new Error("Invalid authorization request. Call blog_auth_request once and reuse its auth_token.");
  }
  const deadline = Math.min(Date.now() + maxWaitMs, request.expiresAt);
  const intervalMs = Math.max(request.interval, 2) * 1e3;
  for (; ; ) {
    if (Date.now() >= request.expiresAt) {
      return { status: "expired", ownerSession: null, timeRemaining: 0, detail: "The approval window closed. Start authentication once more." };
    }
    const result = await exchangeDeviceCode(request.deviceCode);
    if (result.state === "approved") {
      const user = await githubUser(result.token);
      if (user.login.toLowerCase() !== ADMIN_LOGIN) {
        return { status: "denied", ownerSession: null, timeRemaining: 0, detail: `Signed in as ${user.login}. Only ${ADMIN_LOGIN} can author posts.` };
      }
      const ownerSession = await seal({ purpose: "owner-session", token: result.token, login: user.login, expiresAt: Date.now() + SESSION_TTL_MS });
      return { status: "approved", ownerSession, timeRemaining: 0, detail: "Owner verified. Resume the pending authoring request now." };
    }
    if (result.state === "denied" || result.state === "expired") {
      return { status: result.state, ownerSession: null, timeRemaining: secondsLeft(request.expiresAt), detail: result.detail };
    }
    if (Date.now() + intervalMs >= deadline) {
      return {
        status: "pending",
        ownerSession: null,
        timeRemaining: secondsLeft(request.expiresAt),
        detail: "Waiting for GitHub approval. Call blog_auth_verify again with the same auth_token."
      };
    }
    await sleep(intervalMs);
  }
}
async function authorizedGitHub(handle) {
  const session = await unseal(handle);
  if (session.purpose !== "owner-session") throw new Error("Invalid owner session.");
  if (session.expiresAt <= Date.now()) throw new Error("Authorization expired. Run blog_auth_request again.");
  if (session.login.toLowerCase() !== ADMIN_LOGIN) throw new Error("This GitHub account cannot publish.");
  return { token: session.token, login: session.login };
}

// src/lib/mcp-admin/response.ts
var serialize = (payload) => JSON.stringify(payload, null, 2);
async function respond(operation, run) {
  const startedAt = Date.now();
  const timestamp = () => (/* @__PURE__ */ new Date()).toISOString();
  try {
    const outcome = await run();
    const payload = {
      success: true,
      data: outcome.data,
      userMessage: outcome.userMessage,
      meta: {
        operation,
        durationMs: Date.now() - startedAt,
        timestamp: timestamp(),
        nextSteps: outcome.nextSteps
      }
    };
    return {
      content: [{ type: "text", text: serialize(payload) }],
      structuredContent: payload
    };
  } catch (error) {
    const failure = toOperationError(error);
    const payload = {
      success: false,
      error: {
        code: failure.code,
        message: failure.message,
        field: failure.field,
        guidance: failure.guidance,
        suggestion: failure.guidance
      },
      meta: {
        operation,
        durationMs: Date.now() - startedAt,
        timestamp: timestamp(),
        nextSteps: failure.nextSteps
      }
    };
    return {
      content: [{ type: "text", text: serialize(payload) }],
      structuredContent: payload,
      isError: true
    };
  }
}
async function requireOwner(sessionToken) {
  if (!sessionToken?.trim()) {
    throw new OperationError("AUTH_REQUIRED", "No session token was supplied.", {
      field: "session_token",
      guidance: "Call blog_auth_request, poll blog_auth_verify until approved, then retry with the returned session_token.",
      nextSteps: ["blog_auth_request", "blog_auth_verify"]
    });
  }
  try {
    return await authorizedGitHub(sessionToken);
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    throw new OperationError("AUTH_EXPIRED", message, {
      field: "session_token",
      guidance: "The session is no longer valid. Call blog_auth_request to create a new one, then retry this operation.",
      nextSteps: ["blog_auth_request", "blog_auth_verify"]
    });
  }
}
function ownerOperation(operation, sessionToken, run) {
  return respond(operation, async () => run(await requireOwner(sessionToken)));
}

// src/lib/mcp-admin/tools/mcp-schema-get.ts
var mcp_schema_get_default = defineTool({
  name: "mcp_schema_get",
  title: "Describe this server",
  description: "Return the complete contract of this server: tool catalogue, response envelope, error codes, and the authoring and editing workflows. Call this first when unsure which tool to use.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => respond("mcp_schema_get", () => ({
    data: {
      server: {
        name: "somrit-webcv-admin",
        title: "Somrit Dasgupta \u2014 Site Admin",
        owner: "somritdasgupta",
        purpose: "Author and maintain blog posts on somritdasgupta.in, stored as MDX in GitHub."
      },
      naming: {
        pattern: "{domain}_{resource}_{action}",
        domains: ["blog", "mcp"]
      },
      response_envelope: {
        success: "boolean",
        data: "operation payload when success is true",
        error: "{ code, message, field?, guidance? } when success is false",
        userMessage: "single sentence safe to show the user verbatim",
        meta: "{ operation, durationMs, timestamp, nextSteps? }",
        note: "The identical payload is returned in both the text content and structuredContent channels."
      },
      tools: [
        { name: "mcp_schema_get", auth: false, purpose: "Describe this server." },
        { name: "blog_auth_request", auth: false, purpose: "Start owner authorization." },
        { name: "blog_auth_verify", auth: false, purpose: "Poll authorization until approved." },
        { name: "blog_components_list", auth: false, purpose: "List supported MDX components." },
        { name: "blog_posts_suggest_slug", auth: false, purpose: "Derive slug candidates from a title." },
        { name: "blog_posts_validate", auth: false, purpose: "Check a draft against every rule." },
        { name: "blog_posts_list", auth: false, purpose: "List posts including drafts." },
        { name: "blog_posts_read", auth: true, purpose: "Read source, frontmatter, and sha." },
        { name: "blog_posts_create", auth: true, purpose: "Publish a new post." },
        { name: "blog_posts_update", auth: true, purpose: "Edit an existing post." },
        { name: "blog_posts_delete", auth: true, purpose: "Remove a post." },
        { name: "blog_posts_preview", auth: false, purpose: "Show the exact file that would be committed, with validation and MDX compile check." },
        { name: "blog_posts_search", auth: false, purpose: "Ranked full-text search." },
        { name: "blog_posts_by_tag", auth: false, purpose: "Posts carrying a tag plus related tags." },
        { name: "blog_posts_stats", auth: false, purpose: "Aggregate blog statistics." },
        { name: "blog_posts_word_count", auth: false, purpose: "Structural metrics for one post." },
        { name: "blog_posts_related", auth: false, purpose: "Posts sharing tags." },
        { name: "blog_posts_export", auth: false, purpose: "JSON or CSV metadata export." },
        { name: "blog_posts_get_draft_count", auth: true, purpose: "Drafts and scheduled posts." },
        { name: "blog_posts_bulk_update", auth: true, purpose: "Same change on many posts, one commit." },
        { name: "blog_posts_tag_rename", auth: true, purpose: "Rename a tag everywhere, one commit." },
        { name: "blog_posts_validate_bulk", auth: false, purpose: "Validate many drafts." },
        { name: "blog_posts_duplicate", auth: true, purpose: "Copy a post as a draft." },
        { name: "blog_posts_schedule", auth: true, purpose: "Set a future publish date." },
        { name: "blog_posts_import", auth: true, purpose: "Import Markdown, Ghost, or Notion exports." }
      ],
      workflows: {
        publish: [
          "blog_components_list (optional, before rich MDX)",
          "blog_posts_preview \u2014 show the source to the user and wait for approval",
          "blog_auth_request \u2014 show device_code and verification_url only",
          "blog_auth_verify \u2014 repeat with the same auth_token while status is pending",
          "blog_posts_create with session_token",
          "Report success only when published and verified are true and commit_sha is present"
        ],
        edit: [
          "blog_auth_request",
          "blog_auth_verify",
          "blog_posts_read \u2014 keep the returned sha",
          "blog_posts_update with expected_sha"
        ]
      },
      file_format: 'export const frontmatter = { title, description, date: "YYYY-MM-DD", tags?, cover?, draft?, readingTime };  followed by a blank line and the MDX body. Timestamps are reduced to their date part.',
      rules: [
        "Never show auth_token, session_token, or any GitHub token to the user.",
        "Pending authorization is normal \u2014 keep polling, never restart while time remains.",
        "Authorization succeeding is not the same as content changing.",
        "Read before updating or deleting, and pass expected_sha."
      ],
      error_codes: ERROR_CODES
    }
  }))
});

// src/lib/mcp-admin/tools/blog-auth-request.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_auth_request_default = defineTool2({
  name: "blog_auth_request",
  title: "Request publishing authorization",
  description: "Start owner authorization for blog writes. Show device_code and verification_url to the user, keep auth_token internal, then poll blog_auth_verify with that auth_token.",
  inputSchema: {},
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async () => respond("blog_auth_request", async () => {
    const authorization = await createAuthorization();
    return {
      data: {
        device_code: authorization.userCode,
        verification_url: authorization.verificationUri,
        auth_token: authorization.authorizationRequest,
        expires_in_seconds: authorization.expiresIn,
        poll_interval_seconds: authorization.interval,
        poll_until: authorization.pollUntil,
        user_action: `Open ${authorization.verificationUri} and enter the code ${authorization.userCode}.`
      },
      userMessage: `Open ${authorization.verificationUri} and enter the code ${authorization.userCode}. I will continue as soon as GitHub confirms the approval.`,
      nextSteps: ["blog_auth_verify"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-auth-verify.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var blog_auth_verify_default = defineTool3({
  name: "blog_auth_verify",
  title: "Verify publishing authorization",
  description: "Poll the authorization started by blog_auth_request. Repeat with the same auth_token while status is pending. On approved, use the returned session_token for every blog write.",
  inputSchema: {
    auth_token: z.string().min(1).describe("The exact opaque auth_token returned by blog_auth_request. Never shown to the user.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ auth_token }) => respond("blog_auth_verify", async () => {
    const status = await pollAuthorization(auth_token);
    if (status.status === "approved" && status.ownerSession) {
      return {
        data: {
          status: "approved",
          session_token: status.ownerSession,
          expires_in_seconds: 3600,
          guidance: "Use session_token for every blog operation. It is valid for one hour."
        },
        userMessage: "Authorization confirmed. Continuing with the requested change.",
        nextSteps: ["retry the original authoring tool with session_token"]
      };
    }
    if (status.status === "pending") {
      return {
        data: {
          status: "pending",
          seconds_remaining: status.timeRemaining,
          auth_token,
          guidance: "The approval is not confirmed yet. Call blog_auth_verify again with the same auth_token. Do not ask the user to confirm and do not start a new authorization."
        },
        nextSteps: ["blog_auth_verify"]
      };
    }
    throw new OperationError(
      status.status === "denied" ? "AUTH_DENIED" : "AUTH_EXPIRED",
      status.detail,
      {
        field: "auth_token",
        guidance: "Call blog_auth_request to start a new authorization, then poll blog_auth_verify again.",
        nextSteps: ["blog_auth_request", "blog_auth_verify"]
      }
    );
  })
});

// src/lib/mcp-admin/tools/blog-components-list.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/mdx-components.ts
var MDX_COMPONENTS = [
  {
    name: "Callout",
    category: "emphasis",
    purpose: "Highlight a note, tip, warning, danger, or success message.",
    props: [
      { name: "type", type: "enum", description: "Visual style and colour.", values: ["note", "tip", "warning", "danger", "success"] },
      { name: "title", type: "string", description: "Short heading shown above the content." }
    ],
    example: '<Callout type="tip" title="Key idea">\nUseful context.\n</Callout>'
  },
  {
    name: "ProsCons",
    category: "layout",
    purpose: "Compare benefits and drawbacks in two columns.",
    props: [
      { name: "pros", type: "string[]", description: "Benefit lines.", required: true },
      { name: "cons", type: "string[]", description: "Drawback lines.", required: true }
    ],
    example: '<ProsCons pros={["Fast", "Simple"]} cons={["Limited"]} />'
  },
  {
    name: "Quote",
    category: "emphasis",
    purpose: "Render a prominent quotation with attribution.",
    props: [{ name: "author", type: "string", description: "Attribution line." }],
    example: '<Quote author="Author">\nQuoted text.\n</Quote>'
  },
  {
    name: "Kbd",
    category: "inline",
    purpose: "Render an inline keyboard key.",
    props: [],
    example: "<Kbd>Cmd</Kbd> + <Kbd>K</Kbd>"
  },
  {
    name: "LiveCode",
    category: "code",
    purpose: "Embed an editable React playground.",
    props: [
      { name: "template", type: "string", description: 'Sandbox template, typically "react".' },
      { name: "files", type: "object", description: "Map of file path to file contents.", required: true }
    ],
    example: '<LiveCode template="react" files={{ "/App.js": `export default () => <h2>Hello</h2>` }} />'
  },
  {
    name: "Tweet",
    category: "media",
    purpose: "Embed a post from X by its numeric ID.",
    props: [{ name: "id", type: "string", description: "Post ID.", required: true }],
    example: '<Tweet id="1683920951807971329" />'
  },
  {
    name: "Chart",
    category: "data",
    purpose: "Render line, bar, area, pie, or radar data.",
    props: [
      { name: "type", type: "enum", description: "Chart form.", values: ["line", "bar", "area", "pie", "radar"], required: true },
      { name: "title", type: "string", description: "Chart heading." },
      { name: "data", type: "object[]", description: "Row objects keyed by axis and series names.", required: true }
    ],
    example: '<Chart type="line" title="Users" data={[{ week: "W1", users: 120 }, { week: "W2", users: 180 }]} />'
  },
  {
    name: "Stats",
    category: "data",
    purpose: "Show a compact grid of metrics.",
    props: [
      { name: "cols", type: "number", description: "Column count." },
      { name: "items", type: "object[]", description: "Entries of label, value, and optional change.", required: true }
    ],
    example: '<Stats cols={2} items={[{ label: "Posts", value: "42", change: 8 }]} />'
  },
  {
    name: "Tabs",
    category: "layout",
    purpose: "Group related content, typically per language or package manager.",
    props: [{ name: "label", type: "string", description: "Set on each child Tab.", required: true }],
    example: '<Tabs>\n  <Tab label="npm">`npm install pkg`</Tab>\n  <Tab label="bun">`bun add pkg`</Tab>\n</Tabs>'
  },
  {
    name: "Steps",
    category: "layout",
    purpose: "Present a numbered walkthrough.",
    props: [{ name: "title", type: "string", description: "Set on each child Step.", required: true }],
    example: '<Steps>\n  <Step title="Install">Run the command.</Step>\n  <Step title="Configure">Set the variables.</Step>\n</Steps>'
  },
  {
    name: "Accordion",
    category: "layout",
    purpose: "Add collapsible sections or a FAQ block.",
    props: [{ name: "title", type: "string", description: "Set on each child AccordionItem.", required: true }],
    example: '<Accordion>\n  <AccordionItem title="Question?">Answer.</AccordionItem>\n</Accordion>'
  },
  {
    name: "Video",
    category: "media",
    purpose: "Embed a YouTube video or a direct video file.",
    props: [
      { name: "src", type: "string", description: "Video URL.", required: true },
      { name: "caption", type: "string", description: "Caption below the player." }
    ],
    example: '<Video src="https://www.youtube.com/watch?v=VIDEO_ID" caption="Caption" />'
  },
  {
    name: "Badge",
    category: "inline",
    purpose: "Render an inline status label.",
    props: [{ name: "tone", type: "enum", description: "Colour tone.", values: ["default", "success", "warning", "danger"] }],
    example: '<Badge tone="success">stable</Badge>'
  },
  {
    name: "FileTree",
    category: "layout",
    purpose: "Display a directory structure.",
    props: [{ name: "tree", type: "object[]", description: "Nodes of name, type, and children.", required: true }],
    example: '<FileTree tree={[{ name: "src", type: "folder", children: [{ name: "main.tsx" }] }]} />'
  },
  {
    name: "Embed",
    category: "media",
    purpose: "Embed a third-party URL or sandboxed HTML widget.",
    props: [
      { name: "src", type: "string", description: "URL to embed.", required: true },
      { name: "title", type: "string", description: "Accessible frame title." },
      { name: "height", type: "number", description: "Frame height in pixels." }
    ],
    example: '<Embed src="https://codepen.io/team/codepen/pen/PNaGbb" title="Demo" height={420} />'
  }
];
var MDX_BEST_PRACTICES = [
  "Use Callout for warnings and key takeaways rather than bold paragraphs.",
  "Use Tabs to group the same instruction across package managers or languages.",
  "Use Chart or Stats when a claim is numeric; keep raw tables for reference data.",
  "Use LiveCode only for short, self-contained React examples.",
  "Open with a plain paragraph before the first component so previews read well."
];

// src/lib/mcp-admin/tools/blog-components-list.ts
var blog_components_list_default = defineTool4({
  name: "blog_components_list",
  title: "List MDX components",
  description: "Return every custom MDX component the blog renderer supports, with category, props, and a working example. Call this before writing rich MDX.",
  inputSchema: {
    category: z2.enum(["emphasis", "data", "layout", "media", "code", "inline"]).optional().describe("Restrict the result to a single category.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category }) => respond("blog_components_list", () => {
    const components = category ? MDX_COMPONENTS.filter((c) => c.category === category) : MDX_COMPONENTS;
    return {
      data: {
        count: components.length,
        components,
        best_practices: MDX_BEST_PRACTICES,
        notes: [
          "Standard Markdown works everywhere; these components are additions.",
          "Do not include frontmatter in the body \u2014 the tools generate it."
        ]
      },
      nextSteps: ["blog_posts_validate", "blog_posts_create"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-suggest-slug.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/fields.ts
import { z as z3 } from "npm:zod@^3.25.76";
var SLUG_PATTERN = /^[a-z0-9]([a-z0-9-]*[a-z0-9])?$/;
var sessionTokenField = z3.string().min(1).describe(
  'Opaque owner session returned by blog_auth_verify. Valid for one hour. Never a GitHub token and never shown to the user. Example: "owner_session_...".'
);
var slugField = z3.string().min(1).describe(
  'URL-safe slug in kebab-case, normalized to lowercase. Pattern ^[a-z0-9]([a-z0-9-]*[a-z0-9])?$. Examples: "hello-world", "mcp-integration-test".'
);
var titleField = z3.string().trim().min(1).max(120).describe(
  'Post title, 1-120 characters. Used in the page heading and meta tags. Examples: "MCP Integration Test", "Getting Started with Claude".'
);
var descriptionField = z3.string().trim().min(20).max(160).describe(
  'SEO meta description, 20-160 characters. Example: "A short introduction to MCP servers and how they work".'
);
var bodyField = z3.string().min(1).describe(
  "Complete post body in Markdown/MDX without frontmatter. Custom components listed by blog_components_list are supported."
);
var dateField = z3.string().optional().describe(
  'Publish date stored as YYYY-MM-DD. Defaults to today (UTC). A timestamp such as "2026-09-07T14:30:00Z" is reduced to "2026-09-07". A future date schedules the post. Example: "2026-09-07".'
);
var tagsField = z3.array(z3.string().trim().min(1)).max(8).optional().describe('Topic tags for filtering, maximum 8. Example: ["mcp", "api", "integration"].');
var coverField = z3.string().url().optional().describe(
  'Absolute URL of the cover image. 1200x630 is recommended for social previews. Example: "https://example.com/images/cover.png".'
);
var draftField = z3.boolean().optional().describe("Hide the post from the public site when true. Defaults to false.");
var expectedShaField = z3.string().optional().describe(
  "Blob SHA returned by blog_posts_read. The write is rejected when the file changed since that read."
);
var postContentShape = {
  slug: slugField,
  title: titleField,
  description: descriptionField,
  body: bodyField,
  date: dateField,
  tags: tagsField,
  cover: coverField,
  draft: draftField
};
var postContentObject = z3.object(postContentShape);
var optionalSessionField = z3.string().optional().describe("Owner session from blog_auth_verify. Optional for published content; required to see drafts or scheduled posts.");
var isoDay = z3.string().regex(/^\d{4}-\d{2}-\d{2}$/).describe("Date in YYYY-MM-DD format.");
var dateOnlyField = isoDay;
var dateRangeField = z3.object({ from: isoDay.optional(), to: isoDay.optional() }).optional().describe('Inclusive date range, both ends optional. Example: {"from": "2025-01-01", "to": "2025-12-31"}.');
var sortField = z3.enum(["date-desc", "date-asc", "title", "reading-time"]).optional().describe("Sort order. Defaults to date-desc.");

// src/lib/mcp-admin/mdx.ts
var DATE_ONLY = /^(\d{4})-(\d{2})-(\d{2})/;
function toDateOnly(input) {
  const value = String(input ?? "").trim();
  const match = value.match(DATE_ONLY);
  if (match) {
    const [, y, m, d] = match;
    const probe = new Date(Date.UTC(+y, +m - 1, +d));
    const valid = probe.getUTCFullYear() === +y && probe.getUTCMonth() === +m - 1 && probe.getUTCDate() === +d;
    return valid ? `${y}-${m}-${d}` : null;
  }
  const parsed = new Date(value);
  return Number.isNaN(parsed.getTime()) ? null : parsed.toISOString().slice(0, 10);
}
var todayDateOnly = () => (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
var quote = (s) => JSON.stringify(s);
function buildMdx(fm, body) {
  const lines = [
    "export const frontmatter = {",
    `  title: ${quote(fm.title)},`,
    `  description: ${quote(fm.description)},`,
    `  date: ${quote(toDateOnly(fm.date) ?? todayDateOnly())},`
  ];
  if (fm.tags?.length) lines.push(`  tags: [${fm.tags.map(quote).join(", ")}],`);
  if (fm.cover) lines.push(`  cover: ${quote(fm.cover)},`);
  if (fm.draft) lines.push("  draft: true,");
  if (typeof fm.readingTime === "number") lines.push(`  readingTime: ${fm.readingTime},`);
  lines.push("};", "");
  return `${lines.join("\n")}
${body.replace(/^\n+/, "").trimEnd()}
`;
}
var EXPORT_RE = /^\s*export\s+const\s+frontmatter\s*=\s*\{([\s\S]*?)\n\}\s*;?[ \t]*\n?/;
var YAML_RE = /^---\s*\n([\s\S]*?)\n---\s*\n?/;
var STRING_RE = /^("(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*')/;
function parseString(literal) {
  if (literal.startsWith('"')) {
    try {
      return JSON.parse(literal);
    } catch {
    }
  }
  return literal.slice(1, -1).replace(/\\(['"\\])/g, "$1");
}
function parseScalar(raw) {
  const value = raw.trim().replace(/,$/, "").trim();
  const str2 = value.match(STRING_RE);
  if (str2) return parseString(str2[1]);
  if (value.startsWith("[")) {
    const items = value.slice(1, value.lastIndexOf("]")).match(/"(?:\\.|[^"\\])*"|'(?:\\.|[^'\\])*'|[^,\s][^,]*/g) ?? [];
    return items.map((item) => STRING_RE.test(item.trim()) ? parseString(item.trim()) : item.trim()).filter(Boolean);
  }
  if (value === "true" || value === "false") return value === "true";
  if (/^-?\d+(\.\d+)?$/.test(value)) return Number(value);
  return value;
}
function parsePairs(block) {
  const data = {};
  const pattern = /^\s*["']?(\w+)["']?\s*:\s*([\s\S]*?)(?=^\s*["']?\w+["']?\s*:|(?![\s\S]))/gm;
  for (const [, key, raw] of block.matchAll(pattern)) {
    data[key] = parseScalar(raw.replace(/\s*\n\s*/g, " "));
  }
  return data;
}
function parseFrontmatter(src) {
  const text = typeof src === "string" ? src : "";
  const match = text.match(EXPORT_RE) ?? text.match(YAML_RE);
  if (!match) return { data: {}, body: text };
  const data = parsePairs(match[1]);
  if (typeof data.date === "string") data.date = toDateOnly(data.date) ?? data.date;
  return { data, body: text.slice(match[0].length).replace(/^\n+/, "") };
}
function stripMdx(body) {
  return body.replace(/```[\s\S]*?```/g, " ").replace(/^\s*(import|export)\s.*$/gm, " ").replace(/<[^>]*>/g, " ").replace(/[#>*_`~\[\]()|-]/g, " ");
}
var countWords = (body) => stripMdx(body).split(/\s+/).filter(Boolean).length;
var estimateReadingTime = (body) => Math.max(1, Math.round(countWords(body) / 220));

// src/lib/mcp-admin/validation.ts
function normalizeSlug(input) {
  const slug = input.toLowerCase().trim().replace(/\.mdx$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80).replace(/-+$/, "");
  if (!slug || !SLUG_PATTERN.test(slug)) {
    throw new OperationError("INVALID_SLUG", `"${input}" cannot be turned into a valid slug.`, {
      field: "slug",
      guidance: 'Supply a slug containing at least one letter or digit, for example "hello-world".'
    });
  }
  return slug;
}
function collectIssues(input, options) {
  const issues = [];
  const required = options.requireAll;
  const missing = (field, guidance) => issues.push({ field, code: "VALIDATION_ERROR", message: `${field} is required.`, guidance });
  if (input.title === void 0) {
    if (required) missing("title", "Provide a title of 1-120 characters.");
  } else if (input.title.trim().length === 0) {
    issues.push({ field: "title", code: "VALIDATION_ERROR", message: "Title is empty.", guidance: "Provide a title of 1-120 characters." });
  } else if (input.title.length > 120) {
    issues.push({
      field: "title",
      code: "TITLE_TOO_LONG",
      message: `Title exceeds 120 characters (current: ${input.title.length}).`,
      guidance: `Shorten the title by ${input.title.length - 120} characters.`
    });
  }
  if (input.description === void 0) {
    if (required) missing("description", "Provide a meta description of 20-160 characters.");
  } else if (input.description.length < 20 || input.description.length > 160) {
    issues.push({
      field: "description",
      code: "VALIDATION_ERROR",
      message: `Description must be 20-160 characters (current: ${input.description.length}).`,
      guidance: "Rewrite the description to fit the 20-160 character range used for search previews."
    });
  }
  if (input.body === void 0) {
    if (required) missing("body", "Provide the MDX body without frontmatter.");
  } else if (input.body.trim().length === 0) {
    issues.push({ field: "body", code: "VALIDATION_ERROR", message: "Body is empty.", guidance: "Provide the MDX body without frontmatter." });
  }
  if (input.slug === void 0) {
    if (required) missing("slug", "Provide a kebab-case slug, or call blog_posts_suggest_slug with the title.");
  } else {
    try {
      normalizeSlug(input.slug);
    } catch {
      issues.push({
        field: "slug",
        code: "INVALID_SLUG",
        message: `"${input.slug}" is not a usable slug.`,
        guidance: "Call blog_posts_suggest_slug with the title to obtain valid alternatives."
      });
    }
  }
  if (input.date !== void 0 && toDateOnly(input.date) === null) {
    issues.push({
      field: "date",
      code: "INVALID_DATE",
      message: `"${input.date}" is not a valid calendar date.`,
      guidance: 'Use the YYYY-MM-DD format, for example "2026-09-07".'
    });
  }
  if (input.tags && input.tags.length > 8) {
    issues.push({
      field: "tags",
      code: "VALIDATION_ERROR",
      message: `Too many tags (${input.tags.length}). Maximum is 8.`,
      guidance: "Keep the eight most relevant tags and remove the rest."
    });
  }
  if (input.cover !== void 0 && !/^https?:\/\/\S+$/.test(input.cover)) {
    issues.push({
      field: "cover",
      code: "VALIDATION_ERROR",
      message: "Cover must be an absolute http(s) URL.",
      guidance: 'Supply a full URL such as "https://example.com/images/cover.png".'
    });
  }
  return issues;
}
function assertValid(input, options) {
  const [issue] = collectIssues(input, options);
  if (!issue) return;
  throw new OperationError(issue.code, issue.message, {
    field: issue.field,
    guidance: issue.guidance,
    nextSteps: ["blog_posts_validate", "retry the original operation"]
  });
}
function slugCandidates(title) {
  const base = normalizeSlug(title);
  const words = base.split("-").filter(Boolean);
  const shortened = words.slice(0, 4).join("-");
  const candidates = [base, `${base}-2`, `${base}-3`, shortened, `${base}-${(/* @__PURE__ */ new Date()).getFullYear()}`];
  return [...new Set(candidates)].filter((value) => SLUG_PATTERN.test(value));
}

// src/lib/mcp-admin/tools/blog-posts-suggest-slug.ts
var blog_posts_suggest_slug_default = defineTool5({
  name: "blog_posts_suggest_slug",
  title: "Suggest a slug",
  description: "Turn a title into valid kebab-case slug candidates. Requires no authorization. Use the first candidate unless it is already taken.",
  inputSchema: { title: z4.string().min(1).describe("The post title to derive slugs from.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ title }) => respond("blog_posts_suggest_slug", () => ({
    data: { preferred: normalizeSlug(title), candidates: slugCandidates(title) },
    nextSteps: ["blog_posts_validate", "blog_posts_create"]
  }))
});

// src/lib/mcp-admin/tools/blog-posts-validate.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
var blog_posts_validate_default = defineTool6({
  name: "blog_posts_validate",
  title: "Validate a draft",
  description: "Check a draft against every publishing rule and return all problems at once. Requires no authorization. Run this before blog_posts_create to avoid a failed commit.",
  inputSchema: {
    title: z5.string().optional().describe("Proposed title."),
    slug: z5.string().optional().describe("Proposed slug."),
    description: z5.string().optional().describe("Proposed meta description."),
    body: z5.string().optional().describe("Proposed MDX body without frontmatter."),
    date: z5.string().optional().describe("Proposed publish date. YYYY-MM-DD preferred; ISO timestamps are reduced to their date part."),
    tags: z5.array(z5.string()).optional().describe("Proposed tags."),
    cover: z5.string().optional().describe("Proposed cover image URL.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => respond("blog_posts_validate", () => {
    const issues = collectIssues(input, { requireAll: true });
    let normalized = null;
    try {
      normalized = input.slug ? normalizeSlug(input.slug) : input.title ? normalizeSlug(input.title) : null;
    } catch {
      normalized = null;
    }
    return {
      data: {
        normalized_date: input.date ? toDateOnly(input.date) : todayDateOnly(),
        valid: issues.length === 0,
        issues,
        normalized_slug: normalized,
        slug_suggestions: input.title ? slugCandidates(input.title) : []
      },
      userMessage: issues.length === 0 ? "The draft satisfies every publishing rule." : `The draft has ${issues.length} problem${issues.length === 1 ? "" : "s"} to fix before publishing.`,
      nextSteps: issues.length === 0 ? ["blog_auth_request", "blog_posts_create"] : ["fix the listed fields", "blog_posts_validate"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-list.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/github.ts
var REPO = {
  owner: "somritdasgupta",
  name: "webCV",
  branch: "main",
  contentDir: "content/blog"
};
var API = `https://api.github.com/repos/${REPO.owner}/${REPO.name}`;
var headers = (token) => ({
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
  ...token ? { Authorization: `Bearer ${token}` } : {},
  "User-Agent": "somrit-webcv-mcp",
  "X-GitHub-Api-Version": "2022-11-28"
});
var toB64 = (s) => {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
};
var fromB64 = (s) => {
  const bin = atob(s.replace(/\n/g, ""));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
};
async function ghFetch(token, url, init) {
  const res = await fetch(url, { ...init, headers: headers(token) });
  return res;
}
async function fail(res, action) {
  const body = await res.text();
  let message = body;
  try {
    const parsed = JSON.parse(body);
    message = parsed.message ?? body;
    if (parsed.errors) message += ` \u2014 ${JSON.stringify(parsed.errors)}`;
  } catch {
  }
  throw new Error(`${action} failed (${res.status}): ${message}`);
}
var pathForSlug = (slug) => `${REPO.contentDir}/${slug}.mdx`;
async function listPostFiles(token) {
  const res = await ghFetch(
    token,
    `${API}/contents/${REPO.contentDir}?ref=${REPO.branch}`
  );
  if (res.status === 404) return [];
  if (!res.ok) await fail(res, "List posts");
  const data = await res.json();
  return data.filter((f) => f.type === "file" && f.name.endsWith(".mdx")).map(({ name, path, sha }) => ({ name, path, sha }));
}
async function readFile(token, path) {
  const res = await ghFetch(
    token,
    `${API}/contents/${encodeURI(path)}?ref=${REPO.branch}`
  );
  if (res.status === 404) return null;
  if (!res.ok) await fail(res, "Read file");
  const data = await res.json();
  return { content: fromB64(data.content), sha: data.sha };
}
async function writeFile(opts) {
  const res = await ghFetch(opts.token, `${API}/contents/${encodeURI(opts.path)}`, {
    method: "PUT",
    body: JSON.stringify({
      message: opts.message,
      content: toB64(opts.content),
      branch: REPO.branch,
      ...opts.sha ? { sha: opts.sha } : {}
    })
  });
  if (!res.ok) await fail(res, "Commit");
  const data = await res.json();
  return {
    commitSha: data.commit.sha,
    fileSha: data.content.sha,
    htmlUrl: data.content.html_url
  };
}
async function deleteFile(opts) {
  const res = await ghFetch(opts.token, `${API}/contents/${encodeURI(opts.path)}`, {
    method: "DELETE",
    body: JSON.stringify({
      message: opts.message,
      sha: opts.sha,
      branch: REPO.branch
    })
  });
  if (!res.ok) await fail(res, "Delete");
  const data = await res.json();
  return { commitSha: data.commit.sha };
}
async function readRaw(path) {
  const res = await fetch(`https://raw.githubusercontent.com/${REPO.owner}/${REPO.name}/${REPO.branch}/${path}`);
  if (res.status === 404) return null;
  if (!res.ok) await fail(res, "Read file");
  return await res.text();
}
async function commitFiles(token, changes, message) {
  const refRes = await ghFetch(token, `${API}/git/ref/heads/${REPO.branch}`);
  if (!refRes.ok) await fail(refRes, "Read branch");
  const head = (await refRes.json()).object.sha;
  const commitRes = await ghFetch(token, `${API}/git/commits/${head}`);
  if (!commitRes.ok) await fail(commitRes, "Read commit");
  const baseTree = (await commitRes.json()).tree.sha;
  const treeRes = await ghFetch(token, `${API}/git/trees`, {
    method: "POST",
    body: JSON.stringify({
      base_tree: baseTree,
      tree: changes.map(
        (c) => c.content === null ? { path: c.path, mode: "100644", type: "blob", sha: null } : { path: c.path, mode: "100644", type: "blob", content: c.content }
      )
    })
  });
  if (!treeRes.ok) await fail(treeRes, "Create tree");
  const tree = (await treeRes.json()).sha;
  const newCommitRes = await ghFetch(token, `${API}/git/commits`, {
    method: "POST",
    body: JSON.stringify({ message, tree, parents: [head] })
  });
  if (!newCommitRes.ok) await fail(newCommitRes, "Create commit");
  const commitSha = (await newCommitRes.json()).sha;
  const updateRes = await ghFetch(token, `${API}/git/refs/heads/${REPO.branch}`, {
    method: "PATCH",
    body: JSON.stringify({ sha: commitSha, force: false })
  });
  if (!updateRes.ok) await fail(updateRes, "Update branch");
  return { commitSha };
}

// src/lib/mcp-admin/corpus.ts
var SITE = "https://somritdasgupta.in";
function toRecord(slug, path, sha, source) {
  const { data, body } = parseFrontmatter(source);
  const date = typeof data.date === "string" ? data.date : "";
  return {
    slug,
    path,
    sha,
    title: String(data.title ?? slug),
    description: String(data.description ?? ""),
    date,
    tags: Array.isArray(data.tags) ? data.tags.map(String) : [],
    cover: data.cover ? String(data.cover) : void 0,
    draft: data.draft === true,
    scheduled: data.draft !== true && date > todayDateOnly(),
    readingTime: typeof data.readingTime === "number" ? data.readingTime : estimateReadingTime(body),
    wordCount: countWords(body),
    body,
    source,
    url: `${SITE}/blog/${slug}`
  };
}
async function loadCorpus(token) {
  const files = await listPostFiles(token);
  const records = await Promise.all(
    files.map(async (file) => {
      const slug = file.name.replace(/\.mdx$/, "");
      const source = token ? (await readFile(token, file.path))?.content : await readRaw(file.path);
      return source === null || source === void 0 ? null : toRecord(slug, file.path, file.sha, source);
    })
  );
  return records.filter((r) => r !== null);
}
async function loadPost(token, slug) {
  const path = pathForSlug(slug);
  const file = token ? await readFile(token, path) : null;
  const source = token ? file?.content : await readRaw(path);
  if (!source) {
    throw new OperationError("POST_NOT_FOUND", `No post exists with slug "${slug}".`, {
      field: "slug",
      guidance: "Call blog_posts_list or blog_posts_search to find the correct slug.",
      nextSteps: ["blog_posts_list"]
    });
  }
  return toRecord(slug, path, file?.sha ?? "", source);
}
async function readerToken(sessionToken, wantsDrafts) {
  if (sessionToken?.trim()) return (await requireOwner(sessionToken)).token;
  if (wantsDrafts) await requireOwner("");
  return void 0;
}
var isPublic = (p) => !p.draft && !p.scheduled;
var summarize = (p) => ({
  slug: p.slug,
  title: p.title,
  description: p.description,
  date: p.date,
  tags: p.tags,
  readingTime: p.readingTime,
  draft: p.draft,
  scheduled: p.scheduled,
  sha: p.sha,
  url: p.url
});
function scorePost(p, query) {
  const q = query.trim().toLowerCase();
  if (!q) return null;
  const grade = (text) => {
    const t = text.toLowerCase();
    if (t === q) return 1;
    if (t.startsWith(q) || t.split(/\s+/).some((w) => w.startsWith(q))) return 0.75;
    return t.includes(q) ? 0.5 : 0;
  };
  const candidates = [
    ["title", grade(p.title) * 100],
    ["tag", Math.max(0, ...p.tags.map(grade)) * 90],
    ["description", grade(p.description) * 70],
    ["body", grade(stripMdx(p.body)) * 50]
  ];
  const [matchType, score] = candidates.sort((a, b) => b[1] - a[1])[0];
  return score > 0 ? { matchType, score: Math.round(score) } : null;
}
function sortPosts(posts, sort = "date-desc") {
  const copy = [...posts];
  const compare = {
    "date-desc": (a, b) => b.date.localeCompare(a.date),
    "date-asc": (a, b) => a.date.localeCompare(b.date),
    title: (a, b) => a.title.localeCompare(b.title),
    "reading-time": (a, b) => b.readingTime - a.readingTime
  };
  return copy.sort(compare[sort]);
}
var inDateRange = (date, range) => (!range?.from || date >= range.from) && (!range?.to || date <= range.to);
var hasTag = (p, tag) => p.tags.some((t) => t.toLowerCase() === tag.toLowerCase());
function tagFrequency(posts) {
  const freq = {};
  for (const p of posts) for (const t of p.tags) freq[t] = (freq[t] ?? 0) + 1;
  return freq;
}
var daysBetween = (a, b) => Math.round((Date.parse(`${b}T00:00:00Z`) - Date.parse(`${a}T00:00:00Z`)) / 864e5);

// src/lib/mcp-admin/tools/blog-posts-list.ts
var blog_posts_list_default = defineTool7({
  name: "blog_posts_list",
  title: "List posts",
  description: "List posts with optional full-text query, tag filter (post must carry ALL tags), date range, sorting, and limit/offset pagination. Published posts need no session; drafts and scheduled posts require session_token.",
  inputSchema: {
    session_token: optionalSessionField,
    include_drafts: z6.boolean().optional().describe("Include drafts and scheduled posts. Defaults to true with a session, false without."),
    query: z6.string().optional().describe("Case-insensitive search across title, description, tags, and body."),
    tags: z6.array(z6.string()).optional().describe("Return only posts carrying every listed tag."),
    dateRange: dateRangeField,
    sort: sortField,
    limit: z6.number().int().min(1).max(200).optional().describe("Page size, 1-200. Defaults to 100."),
    offset: z6.number().int().min(0).optional().describe("Number of results to skip. Defaults to 0.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async (input) => respond("blog_posts_list", async () => {
    const token = await readerToken(input.session_token, input.include_drafts === true);
    const includeDrafts = input.include_drafts ?? Boolean(token);
    const all = await loadCorpus(token);
    const filtered = all.filter((p) => includeDrafts || isPublic(p)).filter((p) => (input.tags ?? []).every((t) => hasTag(p, t))).filter((p) => inDateRange(p.date, input.dateRange)).filter((p) => !input.query || scorePost(p, input.query) !== null);
    const sorted = sortPosts(filtered, input.sort);
    const offset = input.offset ?? 0;
    const page = sorted.slice(offset, offset + (input.limit ?? 100)).map(summarize);
    return {
      data: {
        posts: page,
        total: sorted.length,
        returned: page.length,
        hasMore: offset + page.length < sorted.length,
        filters_applied: {
          include_drafts: includeDrafts,
          query: input.query ?? null,
          tags: input.tags ?? [],
          dateRange: input.dateRange ?? null,
          sort: input.sort ?? "date-desc",
          limit: input.limit ?? 100,
          offset
        }
      },
      userMessage: `Found ${sorted.length} post${sorted.length === 1 ? "" : "s"}.`,
      nextSteps: ["blog_posts_read"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-read.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_read_default = defineTool8({
  name: "blog_posts_read",
  title: "Read a post",
  description: "Read one post's frontmatter, body, and blob sha. Always read before updating or deleting, and pass the returned sha as expected_sha.",
  inputSchema: { session_token: sessionTokenField, slug: slugField },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token, slug }) => ownerOperation("blog_posts_read", session_token, async (owner) => {
    const safe = normalizeSlug(slug);
    const file = await readFile(owner.token, pathForSlug(safe));
    if (!file) {
      throw new OperationError("POST_NOT_FOUND", `No post exists with slug "${safe}".`, {
        field: "slug",
        guidance: "Call blog_posts_list to see the available slugs.",
        nextSteps: ["blog_posts_list"]
      });
    }
    const { data, body } = parseFrontmatter(file.content);
    return {
      data: {
        slug: safe,
        sha: file.sha,
        frontmatter: data,
        date: typeof data.date === "string" ? data.date : null,
        body,
        source: file.content,
        url: `https://somritdasgupta.in/blog/${safe}`
      },
      nextSteps: ["blog_posts_update", "blog_posts_delete"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-create.ts
import { defineTool as defineTool9 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_create_default = defineTool9({
  name: "blog_posts_create",
  title: "Create a post",
  description: "Validate and publish a new post as an MDX commit. Fails if the slug already exists. Report success only when published is true and a commit_sha is returned.",
  inputSchema: { session_token: sessionTokenField, ...postContentShape },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => ownerOperation("blog_posts_create", input.session_token, async (owner) => {
    assertValid(input, { requireAll: true });
    const slug = normalizeSlug(input.slug);
    const path = pathForSlug(slug);
    if (await readFile(owner.token, path)) {
      throw new OperationError("SLUG_EXISTS", `A post already exists at "${slug}".`, {
        field: "slug",
        guidance: `Choose a different slug, for example ${slugCandidates(input.title).slice(1, 3).join(" or ")}, or call blog_posts_update to edit the existing post.`,
        nextSteps: ["blog_posts_update"]
      });
    }
    const date = input.date ? toDateOnly(input.date) : todayDateOnly();
    const source = buildMdx(
      {
        title: input.title,
        description: input.description,
        date,
        tags: input.tags,
        cover: input.cover,
        draft: input.draft,
        readingTime: estimateReadingTime(input.body)
      },
      input.body
    );
    const commit = await writeFile({
      token: owner.token,
      path,
      content: source,
      message: `content: add ${slug}`
    });
    const verified = Boolean(await readFile(owner.token, path));
    if (!verified) {
      throw new OperationError("COMMIT_FAILED", "The commit was accepted but the file could not be read back.", {
        guidance: "Call blog_posts_read with the same slug to confirm the current state before retrying.",
        nextSteps: ["blog_posts_read"]
      });
    }
    const scheduled = date > todayDateOnly();
    return {
      data: {
        published: true,
        verified: true,
        slug,
        path,
        draft: input.draft === true,
        scheduled,
        date,
        commit_sha: commit.commitSha,
        sha: commit.fileSha,
        url: `https://somritdasgupta.in/blog/${slug}`,
        commit_url: commit.htmlUrl
      },
      userMessage: input.draft ? `Saved "${input.title}" as a draft. It stays hidden until the draft flag is removed.` : scheduled ? `Scheduled "${input.title}" for ${date}.` : `Published "${input.title}" at https://somritdasgupta.in/blog/${slug}.`,
      nextSteps: ["blog_posts_read"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-update.ts
import { defineTool as defineTool10 } from "npm:@lovable.dev/mcp-js@0.20.1";
var optional = (schema) => schema.optional();
var blog_posts_update_default = defineTool10({
  name: "blog_posts_update",
  title: "Update a post",
  description: "Update an existing post. Only the supplied fields change. Read the post first and pass expected_sha so a concurrent edit is never overwritten.",
  inputSchema: {
    session_token: sessionTokenField,
    slug: slugField,
    title: optional(titleField),
    description: optional(descriptionField),
    body: optional(bodyField),
    date: dateField,
    tags: tagsField,
    cover: coverField,
    draft: draftField,
    expected_sha: expectedShaField
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async (input) => ownerOperation("blog_posts_update", input.session_token, async (owner) => {
    assertValid(input, { requireAll: false });
    const slug = normalizeSlug(input.slug);
    const path = pathForSlug(slug);
    const current = await readFile(owner.token, path);
    if (!current) {
      throw new OperationError("POST_NOT_FOUND", `No post exists with slug "${slug}".`, {
        field: "slug",
        guidance: "Call blog_posts_list to see the available slugs, or blog_posts_create to add a new post.",
        nextSteps: ["blog_posts_list", "blog_posts_create"]
      });
    }
    if (input.expected_sha && input.expected_sha !== current.sha) {
      throw new OperationError("CONFLICT", "The post changed since it was read.", {
        field: "expected_sha",
        guidance: "Call blog_posts_read again, reapply the edit to the fresh content, then retry with the new sha.",
        nextSteps: ["blog_posts_read"]
      });
    }
    const { data, body } = parseFrontmatter(current.content);
    const nextBody = input.body ?? body;
    const source = buildMdx(
      {
        title: input.title ?? String(data.title ?? slug),
        description: input.description ?? String(data.description ?? ""),
        date: input.date ? toDateOnly(input.date) : String(data.date ?? todayDateOnly()),
        tags: input.tags ?? (Array.isArray(data.tags) ? data.tags : void 0),
        cover: input.cover ?? (data.cover ? String(data.cover) : void 0),
        draft: input.draft ?? data.draft === true,
        readingTime: estimateReadingTime(nextBody)
      },
      nextBody
    );
    const commit = await writeFile({
      token: owner.token,
      path,
      content: source,
      message: `content: update ${slug}`,
      sha: current.sha
    });
    return {
      data: {
        updated: true,
        verified: Boolean(await readFile(owner.token, path)),
        slug,
        commit_sha: commit.commitSha,
        sha: commit.fileSha,
        url: `https://somritdasgupta.in/blog/${slug}`,
        commit_url: commit.htmlUrl
      },
      userMessage: `Updated the post "${input.title ?? data.title ?? slug}".`,
      nextSteps: ["blog_posts_read"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-delete.ts
import { defineTool as defineTool11 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z7 } from "npm:zod@^3.25.76";
var blog_posts_delete_default = defineTool11({
  name: "blog_posts_delete",
  title: "Delete a post",
  description: "Permanently remove a post from the repository. Requires explicit confirmation and, when supplied, a matching expected_sha.",
  inputSchema: {
    session_token: sessionTokenField,
    slug: slugField,
    confirm: z7.literal(true).describe("Must be true. Set it only after the user has explicitly asked for the deletion."),
    expected_sha: expectedShaField
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ session_token, slug, expected_sha }) => ownerOperation("blog_posts_delete", session_token, async (owner) => {
    const safe = normalizeSlug(slug);
    const path = pathForSlug(safe);
    const current = await readFile(owner.token, path);
    if (!current) {
      throw new OperationError("POST_NOT_FOUND", `No post exists with slug "${safe}".`, {
        field: "slug",
        guidance: "Call blog_posts_list to see the available slugs.",
        nextSteps: ["blog_posts_list"]
      });
    }
    if (expected_sha && expected_sha !== current.sha) {
      throw new OperationError("CONFLICT", "The post changed since it was read.", {
        field: "expected_sha",
        guidance: "Call blog_posts_read again and retry the deletion with the fresh sha.",
        nextSteps: ["blog_posts_read"]
      });
    }
    const commit = await deleteFile({
      token: owner.token,
      path,
      sha: current.sha,
      message: `content: remove ${safe}`
    });
    return {
      data: {
        deleted: true,
        verified: await readFile(owner.token, path) === null,
        slug: safe,
        commit_sha: commit.commitSha
      },
      userMessage: `Deleted the post "${safe}".`,
      nextSteps: ["blog_posts_list"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-preview.ts
import { defineTool as defineTool12 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { compile } from "npm:@mdx-js/mdx@^3.0.0";
import remarkGfm from "npm:remark-gfm@^4";
async function compileCheck(source) {
  try {
    await compile(source, { remarkPlugins: [remarkGfm] });
    return { ok: true, error: null };
  } catch (error) {
    return { ok: false, error: error instanceof Error ? error.message : String(error) };
  }
}
var blog_posts_preview_default = defineTool12({
  name: "blog_posts_preview",
  title: "Preview a post",
  description: "Show exactly what blog_posts_create would commit, without writing anything: the full .mdx file, normalized metadata, validation issues, and an MDX compile check. Requires no authorization. Show the preview to the user and get approval before publishing.",
  inputSchema: postContentShape,
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (input) => respond("blog_posts_preview", async () => {
    const issues = collectIssues(input, { requireAll: true });
    let slug = null;
    try {
      slug = normalizeSlug(input.slug);
    } catch {
      slug = null;
    }
    const date = input.date && toDateOnly(input.date) || todayDateOnly();
    const frontmatter = {
      title: input.title,
      description: input.description,
      date,
      tags: input.tags,
      cover: input.cover,
      draft: input.draft,
      readingTime: estimateReadingTime(input.body)
    };
    const source = buildMdx(frontmatter, input.body);
    const compiled = await compileCheck(source);
    const ready = issues.length === 0 && compiled.ok && slug !== null;
    return {
      data: {
        ready,
        slug,
        path: slug ? `content/blog/${slug}.mdx` : null,
        url: slug ? `https://somritdasgupta.in/blog/${slug}` : null,
        status: input.draft ? "draft" : date > todayDateOnly() ? "scheduled" : "published",
        frontmatter,
        word_count: countWords(input.body),
        issues,
        compile: compiled,
        source
      },
      userMessage: ready ? "Preview ready. Review the file below; it publishes exactly as shown." : "The preview found problems that must be fixed before publishing.",
      nextSteps: ready ? ["confirm with the user", "blog_auth_request", "blog_posts_create"] : ["fix issues", "blog_posts_preview"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-search.ts
import { defineTool as defineTool13 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z8 } from "npm:zod@^3.25.76";
var blog_posts_search_default = defineTool13({
  name: "blog_posts_search",
  title: "Search posts",
  description: "Full-text search across title, description, tags, and body (MDX markup stripped). Results are ranked 0-100: exact over prefix over substring, title over tag over description over body. Drafts require session_token.",
  inputSchema: {
    query: z8.string().min(1).describe("Search term. Case-insensitive."),
    filters: z8.object({
      tags: z8.array(z8.string()).optional().describe("Keep posts carrying ANY of these tags."),
      draft: z8.boolean().optional().describe("Include drafts and scheduled posts. Requires session_token."),
      dateRange: dateRangeField
    }).optional(),
    limit: z8.number().int().min(1).max(200).optional().describe("Maximum results, up to 200. Defaults to 50."),
    session_token: optionalSessionField
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ query, filters, limit, session_token }) => respond("blog_posts_search", async () => {
    const token = await readerToken(session_token, filters?.draft === true);
    const posts = await loadCorpus(token);
    const results = posts.filter((p) => filters?.draft === true || isPublic(p)).filter((p) => !filters?.tags?.length || filters.tags.some((t) => hasTag(p, t))).filter((p) => inDateRange(p.date, filters?.dateRange)).map((p) => ({ p, hit: scorePost(p, query) })).filter((r) => r.hit !== null).sort((a, b) => b.hit.score - a.hit.score || b.p.date.localeCompare(a.p.date));
    const page = results.slice(0, limit ?? 50).map(({ p, hit }) => ({
      slug: p.slug,
      title: p.title,
      description: p.description,
      date: p.date,
      tags: p.tags,
      matchType: hit.matchType,
      score: hit.score,
      url: p.url
    }));
    return {
      data: { results: page, total: results.length, query, filters_applied: filters ?? {} },
      userMessage: `${results.length} post${results.length === 1 ? "" : "s"} matched "${query}".`,
      nextSteps: ["blog_posts_read"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-by-tag.ts
import { defineTool as defineTool14 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z9 } from "npm:zod@^3.25.76";
var blog_posts_by_tag_default = defineTool14({
  name: "blog_posts_by_tag",
  title: "Posts by tag",
  description: "Return every post carrying a tag (case-insensitive) plus the five most common co-occurring tags.",
  inputSchema: {
    tag: z9.string().min(1).describe('Tag to look up. Example: "ai".'),
    options: z9.object({
      include_drafts: z9.boolean().optional().describe("Include drafts. Requires session_token. Defaults to false."),
      sort: z9.enum(["date-desc", "date-asc", "title"]).optional().describe("Defaults to date-desc."),
      limit: z9.number().int().min(1).max(200).optional().describe("Defaults to 100.")
    }).optional(),
    session_token: optionalSessionField
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ tag, options, session_token }) => respond("blog_posts_by_tag", async () => {
    const token = await readerToken(session_token, options?.include_drafts === true);
    const matches = (await loadCorpus(token)).filter((p) => options?.include_drafts === true || isPublic(p)).filter((p) => hasTag(p, tag));
    const freq = tagFrequency(matches);
    const related = Object.entries(freq).filter(([t]) => t.toLowerCase() !== tag.toLowerCase()).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([t]) => t);
    const posts = sortPosts(matches, options?.sort).slice(0, options?.limit ?? 100).map((p) => ({ slug: p.slug, title: p.title, description: p.description, date: p.date, readingTime: p.readingTime, tags: p.tags, draft: p.draft }));
    return {
      data: { tag, posts, count: matches.length, related_tags: related },
      userMessage: `${matches.length} post${matches.length === 1 ? "" : "s"} tagged "${tag}".`,
      nextSteps: related.length ? ["blog_posts_by_tag with a related tag"] : []
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-stats.ts
import { defineTool as defineTool15 } from "npm:@lovable.dev/mcp-js@0.20.1";
function publishFrequency(dates) {
  if (dates.length < 3) return "irregular";
  const gaps = dates.slice(1).map((d, i) => daysBetween(dates[i], d)).sort((a, b) => a - b);
  const median = gaps[Math.floor(gaps.length / 2)];
  if (median <= 2) return "daily";
  if (median <= 9) return "weekly";
  if (median <= 18) return "bi-weekly";
  if (median <= 40) return "monthly";
  return "irregular";
}
function buildStats(all) {
  const published = all.filter(isPublic);
  const dates = published.map((p) => p.date).filter(Boolean).sort();
  const reading = published.map((p) => p.readingTime);
  const words = published.reduce((sum, p) => sum + p.wordCount, 0);
  const perMonth = {};
  for (const d of dates) perMonth[d.slice(0, 7)] = (perMonth[d.slice(0, 7)] ?? 0) + 1;
  const freq = tagFrequency(published);
  const top = Object.entries(freq).sort((a, b) => b[1] - a[1]).map(([tag, count]) => ({ tag, count }));
  const oldest = dates[0] ?? null;
  const newest = dates[dates.length - 1] ?? null;
  const avg = (n) => published.length ? Math.round(n / published.length * 10) / 10 : 0;
  return {
    total_posts: all.length,
    draft_count: all.filter((p) => p.draft).length,
    scheduled_count: all.filter((p) => p.scheduled).length,
    published_count: published.length,
    total_words: words,
    avg_words_per_post: avg(words),
    avg_reading_time: avg(reading.reduce((a, b) => a + b, 0)),
    min_reading_time: reading.length ? Math.min(...reading) : 0,
    max_reading_time: reading.length ? Math.max(...reading) : 0,
    oldest_post_date: oldest,
    newest_post_date: newest,
    date_range_days: oldest && newest ? daysBetween(oldest, newest) : 0,
    posts_per_month: perMonth,
    tag_frequency: freq,
    top_tags: top.slice(0, 10),
    most_used_tags: top.slice(0, 5).map((t) => t.tag),
    publish_frequency: publishFrequency(dates),
    last_published: newest,
    streak_current_days: newest ? daysBetween(newest, todayDateOnly()) : null
  };
}
var blog_posts_stats_default = defineTool15({
  name: "blog_posts_stats",
  title: "Blog statistics",
  description: "Aggregate statistics: counts, word totals, reading-time spread, posts per month, tag frequency, publishing cadence, and days since the last published post (streak_current_days). Content figures cover published posts; draft and scheduled counts need session_token to be complete.",
  inputSchema: { session_token: optionalSessionField },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token }) => respond("blog_posts_stats", async () => {
    const token = await readerToken(session_token, false);
    const stats = buildStats(await loadCorpus(token));
    return {
      data: { ...stats, includes_unpublished: Boolean(token) },
      userMessage: `${stats.published_count} published posts, ${stats.total_words} words in total.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-word-count.ts
import { defineTool as defineTool16 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_word_count_default = defineTool16({
  name: "blog_posts_word_count",
  title: "Word count",
  description: "Structural metrics for one post: words and characters of prose (MDX stripped), reading time at 220 wpm, code blocks, component tags, and headings.",
  inputSchema: { slug: slugField, session_token: optionalSessionField },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ slug, session_token }) => respond("blog_posts_word_count", async () => {
    const post = await loadPost(await readerToken(session_token, false), normalizeSlug(slug));
    const prose = stripMdx(post.body).replace(/\s+/g, " ").trim();
    const words = prose ? prose.split(" ").length : 0;
    return {
      data: {
        slug: post.slug,
        word_count: words,
        char_count: prose.length,
        estimated_reading_time: Math.max(1, Math.round(words / 220)),
        code_block_count: (post.body.match(/```[\s\S]*?```/g) ?? []).length,
        component_count: (post.body.match(/<[A-Z][A-Za-z0-9]*/g) ?? []).length,
        headings_count: (post.body.match(/^#{1,6}\s/gm) ?? []).length
      },
      userMessage: `"${post.title}" has ${words} words.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-related.ts
import { defineTool as defineTool17 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z10 } from "npm:zod@^3.25.76";
var blog_posts_related_default = defineTool17({
  name: "blog_posts_related",
  title: "Related posts",
  description: "Published posts sharing tags with the given post, ranked by number of shared tags, then recency.",
  inputSchema: {
    slug: slugField,
    limit: z10.number().int().min(1).max(10).optional().describe("1-10. Defaults to 5."),
    session_token: optionalSessionField
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ slug, limit, session_token }) => respond("blog_posts_related", async () => {
    const safe = normalizeSlug(slug);
    const posts = await loadCorpus(await readerToken(session_token, false));
    const source = posts.find((p) => p.slug === safe);
    if (!source) {
      throw new OperationError("POST_NOT_FOUND", `No post exists with slug "${safe}".`, {
        field: "slug",
        guidance: "Call blog_posts_search to find the correct slug."
      });
    }
    const own = new Set(source.tags.map((t) => t.toLowerCase()));
    const related = posts.filter((p) => p.slug !== safe && isPublic(p)).map((p) => ({ p, common: p.tags.filter((t) => own.has(t.toLowerCase())) })).filter((r) => r.common.length > 0).sort((a, b) => b.common.length - a.common.length || b.p.date.localeCompare(a.p.date));
    return {
      data: {
        slug: safe,
        related: related.slice(0, limit ?? 5).map(({ p, common }) => ({
          slug: p.slug,
          title: p.title,
          description: p.description,
          tags: p.tags,
          commonTags: common,
          commonTagCount: common.length
        })),
        total: related.length
      }
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-export.ts
import { defineTool as defineTool18 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z11 } from "npm:zod@^3.25.76";
var COOLDOWN_MS = 6e4;
var lastExportAt = 0;
var csvField = (value) => {
  const s = String(value);
  return /[",\n\r]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
};
var blog_posts_export_default = defineTool18({
  name: "blog_posts_export",
  title: "Export metadata",
  description: "Export metadata (no bodies) of all published posts as JSON or CSV. Limited to one export per minute.",
  inputSchema: { format: z11.enum(["json", "csv"]).describe("Output format.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ format }) => respond("blog_posts_export", async () => {
    const wait = lastExportAt + COOLDOWN_MS - Date.now();
    if (wait > 0) {
      throw new OperationError("RATE_LIMITED", "Exports are limited to one per minute.", {
        guidance: `Retry in ${Math.ceil(wait / 1e3)} seconds.`
      });
    }
    lastExportAt = Date.now();
    const posts = (await loadCorpus()).filter(isPublic).sort((a, b) => b.date.localeCompare(a.date)).map((p) => ({ slug: p.slug, title: p.title, description: p.description, date: p.date, tags: p.tags, readingTime: p.readingTime, draft: p.draft, url: p.url }));
    const base = { format, total: posts.length, exported_at: todayDateOnly() };
    if (format === "json") return { data: { ...base, posts } };
    const header = "slug,title,description,date,tags,readingTime,draft,url";
    const rows = posts.map(
      (p) => [p.slug, p.title, p.description, p.date, p.tags.join(","), p.readingTime, p.draft, p.url].map(csvField).join(",")
    );
    return { data: { ...base, csv: [header, ...rows].join("\n") } };
  })
});

// src/lib/mcp-admin/tools/blog-posts-get-draft-count.ts
import { defineTool as defineTool19 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_get_draft_count_default = defineTool19({
  name: "blog_posts_get_draft_count",
  title: "Unpublished posts",
  description: "Count drafts and scheduled posts (not drafted, dated in the future) and list them. created_at is the post date; the repository does not track a separate creation time. Requires session_token.",
  inputSchema: { session_token: sessionTokenField },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token }) => ownerOperation("blog_posts_get_draft_count", session_token, async (owner) => {
    const posts = await loadCorpus(owner.token);
    const today = todayDateOnly();
    const unpublished = posts.filter((p) => p.draft || p.scheduled);
    const drafts = posts.filter((p) => p.draft);
    const oldest = drafts.map((p) => p.date).filter(Boolean).sort()[0];
    return {
      data: {
        draft_count: drafts.length,
        scheduled_count: posts.filter((p) => p.scheduled).length,
        total_unpublished: unpublished.length,
        drafts: unpublished.map((p) => ({ slug: p.slug, title: p.title, status: p.draft ? "draft" : "scheduled", created_at: p.date })),
        oldest_draft_age_days: oldest ? Math.max(0, daysBetween(oldest, today)) : 0
      },
      userMessage: `${drafts.length} draft${drafts.length === 1 ? "" : "s"} and ${unpublished.length - drafts.length} scheduled.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-bulk-update.ts
import { defineTool as defineTool20 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z12 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/bulk.ts
var MAX_BATCH = 100;
function rebuild(post, overrides = {}, body = post.body) {
  return buildMdx(
    {
      title: post.title,
      description: post.description,
      date: post.date,
      tags: post.tags.length ? post.tags : void 0,
      cover: post.cover,
      draft: post.draft,
      ...overrides,
      readingTime: estimateReadingTime(body)
    },
    body
  );
}
function assertBatchSize(count, field) {
  if (count > MAX_BATCH) {
    throw new OperationError("LIMIT_EXCEEDED", `At most ${MAX_BATCH} items per call (received ${count}).`, {
      field,
      guidance: `Split the request into batches of ${MAX_BATCH} or fewer.`
    });
  }
}

// src/lib/mcp-admin/tools/blog-posts-bulk-update.ts
var blog_posts_bulk_update_default = defineTool20({
  name: "blog_posts_bulk_update",
  title: "Bulk update posts",
  description: "Apply the same metadata change (tags replace, description, draft, cover) to 1-100 posts in ONE commit. All slugs are checked first; if any is missing nothing is written.",
  inputSchema: {
    session_token: sessionTokenField,
    slugs: z12.array(z12.string().min(1)).min(1).max(100).describe("Slugs to update, 1-100."),
    updates: z12.object({ tags: tagsField, description: descriptionField.optional(), draft: draftField, cover: coverField }).describe("Fields to set on every listed post. At least one is required.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token, slugs, updates }) => ownerOperation("blog_posts_bulk_update", session_token, async (owner) => {
    assertBatchSize(slugs.length, "slugs");
    const fields = Object.entries(updates).filter(([, v]) => v !== void 0);
    if (!fields.length) {
      throw new OperationError("VALIDATION_ERROR", "No update fields were supplied.", {
        field: "updates",
        guidance: "Provide at least one of tags, description, draft, or cover."
      });
    }
    const wanted = [...new Set(slugs.map(normalizeSlug))];
    const bySlug = new Map((await loadCorpus(owner.token)).map((p) => [p.slug, p]));
    const failed = wanted.filter((s) => !bySlug.has(s)).map((slug) => ({ slug, error: "Post not found.", code: "POST_NOT_FOUND" }));
    if (failed.length) {
      throw new OperationError("POST_NOT_FOUND", `${failed.length} slug(s) do not exist: ${failed.map((f) => f.slug).join(", ")}. Nothing was changed.`, {
        field: "slugs",
        guidance: "Remove or correct the missing slugs and retry. Use blog_posts_list to see valid slugs."
      });
    }
    const changes = wanted.map((slug) => ({ path: bySlug.get(slug).path, content: rebuild(bySlug.get(slug), Object.fromEntries(fields)) }));
    const { commitSha } = await commitFiles(owner.token, changes, `content: bulk_update ${wanted.length} posts`);
    return {
      data: { updated: wanted.length, failed: [], commit_sha: commitSha, summary: `Updated ${fields.map(([k]) => k).join(", ")} on ${wanted.length} posts.` },
      userMessage: `Updated ${wanted.length} posts in one commit.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-tag-rename.ts
import { defineTool as defineTool21 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z13 } from "npm:zod@^3.25.76";
var blog_posts_tag_rename_default = defineTool21({
  name: "blog_posts_tag_rename",
  title: "Rename a tag",
  description: "Rename a tag on every post that carries it (case-insensitive), in ONE commit. Other tags are kept; duplicates are merged.",
  inputSchema: {
    session_token: sessionTokenField,
    old_tag: z13.string().trim().min(1).describe("Tag to replace."),
    new_tag: z13.string().trim().min(1).describe("Replacement tag.")
  },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token, old_tag, new_tag }) => ownerOperation("blog_posts_tag_rename", session_token, async (owner) => {
    const affected = (await loadCorpus(owner.token)).filter((p) => hasTag(p, old_tag));
    if (!affected.length) {
      throw new OperationError("TAG_NOT_FOUND", `No post carries the tag "${old_tag}".`, {
        field: "old_tag",
        guidance: "Call blog_posts_stats to see existing tags."
      });
    }
    const changes = affected.map((p) => {
      const tags = [...new Set(p.tags.map((t) => t.toLowerCase() === old_tag.toLowerCase() ? new_tag : t))];
      return { path: p.path, content: rebuild(p, { tags }) };
    });
    const { commitSha } = await commitFiles(owner.token, changes, `content: rename tag ${old_tag} -> ${new_tag}`);
    return {
      data: { old_tag, new_tag, updated_count: affected.length, affected_posts: affected.map((p) => p.slug), commit_sha: commitSha },
      userMessage: `Renamed "${old_tag}" to "${new_tag}" on ${affected.length} posts.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-validate-bulk.ts
import { defineTool as defineTool22 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z14 } from "npm:zod@^3.25.76";
var draftShape = z14.object({
  title: z14.string().optional(),
  slug: z14.string().optional(),
  description: z14.string().optional(),
  body: z14.string().optional(),
  tags: z14.array(z14.string()).optional(),
  cover: z14.string().optional(),
  date: z14.string().optional(),
  draft: z14.boolean().optional()
});
function warningsFor(post) {
  const out = [];
  if (!post.tags?.length) out.push("No tags; the post will not appear in tag filters.");
  if (post.description && post.description.length < 50) out.push("Description is short; 120-160 characters preview best.");
  if (post.body && post.body.trim().split(/\s+/).length < 150) out.push("Body is under 150 words.");
  return out;
}
var blog_posts_validate_bulk_default = defineTool22({
  name: "blog_posts_validate_bulk",
  title: "Validate drafts in bulk",
  description: "Validate up to 100 drafts against the publishing rules. Every draft is checked; all errors and warnings are returned. No authorization required.",
  inputSchema: { posts: z14.array(draftShape).min(1).max(100).describe("Drafts to validate.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ posts }) => respond("blog_posts_validate_bulk", () => {
    assertBatchSize(posts.length, "posts");
    const seen = /* @__PURE__ */ new Map();
    const invalid = [];
    const warnings = [];
    posts.forEach((post, index) => {
      const slug = post.slug ?? "";
      const errors = collectIssues(post, { requireAll: true }).map(({ field, message, code }) => ({ field, message, code }));
      if (slug && seen.has(slug)) errors.push({ field: "slug", code: "SLUG_EXISTS", message: `Duplicates the slug of item ${seen.get(slug)}.` });
      seen.set(slug, index);
      if (errors.length) invalid.push({ index, slug, errors });
      for (const warning of warningsFor(post)) warnings.push({ index, slug, warning });
    });
    return {
      data: { total: posts.length, valid: posts.length - invalid.length, invalid, warnings },
      userMessage: `${posts.length - invalid.length} of ${posts.length} drafts are valid.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-duplicate.ts
import { defineTool as defineTool23 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_duplicate_default = defineTool23({
  name: "blog_posts_duplicate",
  title: "Duplicate a post",
  description: "Copy a post to a new slug as a draft dated today, keeping title, description, tags, cover, and body.",
  inputSchema: { session_token: sessionTokenField, slug: slugField, new_slug: slugField },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ session_token, slug, new_slug }) => ownerOperation("blog_posts_duplicate", session_token, async (owner) => {
    const source = await loadPost(owner.token, normalizeSlug(slug));
    const target = normalizeSlug(new_slug);
    if (await readFile(owner.token, pathForSlug(target))) {
      throw new OperationError("SLUG_EXISTS", `A post already exists at "${target}".`, {
        field: "new_slug",
        guidance: "Choose another new_slug or call blog_posts_suggest_slug."
      });
    }
    const today = todayDateOnly();
    const commit = await writeFile({
      token: owner.token,
      path: pathForSlug(target),
      content: rebuild(source, { draft: true, date: today }),
      message: `content: duplicate ${source.slug} as ${target}`
    });
    return {
      data: { original_slug: source.slug, new_slug: target, draft: true, created_at: today, commit_sha: commit.commitSha, message: "Post duplicated as draft. Edit and publish when ready." },
      userMessage: `Duplicated "${source.title}" as a draft at ${target}.`,
      nextSteps: ["blog_posts_update"]
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-schedule.ts
import { defineTool as defineTool24 } from "npm:@lovable.dev/mcp-js@0.20.1";
var blog_posts_schedule_default = defineTool24({
  name: "blog_posts_schedule",
  title: "Schedule a post",
  description: "Set a future publish date (YYYY-MM-DD) and clear the draft flag. The site shows the post automatically from that date.",
  inputSchema: { session_token: sessionTokenField, slug: slugField, publish_at: dateOnlyField },
  annotations: { readOnlyHint: false, idempotentHint: true, openWorldHint: true },
  handler: async ({ session_token, slug, publish_at }) => ownerOperation("blog_posts_schedule", session_token, async (owner) => {
    const date = toDateOnly(publish_at);
    const today = todayDateOnly();
    if (!date || date <= today) {
      throw new OperationError("INVALID_DATE", `publish_at must be a valid date after ${today}.`, {
        field: "publish_at",
        guidance: "Supply a future date in YYYY-MM-DD format, or use blog_posts_update to publish now."
      });
    }
    const post = await loadPost(owner.token, normalizeSlug(slug));
    const commit = await writeFile({
      token: owner.token,
      path: post.path,
      content: rebuild(post, { date, draft: false }),
      message: `content: schedule ${post.slug} for ${date}`,
      sha: post.sha
    });
    return {
      data: { slug: post.slug, scheduled: true, publishes_at: date, days_until_publish: daysBetween(today, date), current_draft_status: false, commit_sha: commit.commitSha, message: `Post scheduled for publication on ${date}` },
      userMessage: `"${post.title}" will publish on ${date}.`
    };
  })
});

// src/lib/mcp-admin/tools/blog-posts-import.ts
import { defineTool as defineTool25 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z15 } from "npm:zod@^3.25.76";
var str = (v) => typeof v === "string" ? v : v == null ? "" : String(v);
function fromMarkdown(content) {
  return content.split(/^\+\+\+\s*$/m).filter((d) => d.trim()).map((doc) => {
    const { data, body } = parseFrontmatter(doc.trim());
    const heading = body.match(/^#\s+(.+)$/m)?.[1];
    return {
      title: str(data.title) || heading || "",
      slug: data.slug ? str(data.slug) : void 0,
      description: str(data.description),
      body,
      date: data.date ? str(data.date) : void 0,
      tags: Array.isArray(data.tags) ? data.tags.map(str) : void 0,
      draft: data.draft === true
    };
  });
}
function fromGhost(content) {
  const db = JSON.parse(content);
  const data = db.db?.[0]?.data ?? db.data ?? db;
  const tagNames = new Map((data.tags ?? []).map((t) => [t.id, t.name]));
  return (data.posts ?? []).map((p) => ({
    title: str(p.title),
    slug: p.slug,
    description: str(p.custom_excerpt || p.meta_description || p.plaintext?.slice(0, 157)),
    body: str(p.markdown || p.plaintext || p.html),
    date: p.published_at ?? p.created_at,
    tags: (data.posts_tags ?? []).filter((pt) => pt.post_id === p.id).map((pt) => str(tagNames.get(pt.tag_id))).filter(Boolean),
    draft: p.status !== "published"
  }));
}
function fromNotion(content) {
  const rows = JSON.parse(content);
  const list = Array.isArray(rows) ? rows : rows.results ?? [rows];
  return list.map((r) => {
    const tags = r.tags ?? r.Tags;
    return {
      title: str(r.title ?? r.Title ?? r.Name ?? r.name),
      slug: r.slug ?? r.Slug,
      description: str(r.description ?? r.Description ?? r.summary),
      body: str(r.body ?? r.content ?? r.Content ?? r.markdown),
      date: r.date ?? r.Date ?? r.created_time,
      tags: Array.isArray(tags) ? tags.map(str) : typeof tags === "string" ? tags.split(",").map((t) => t.trim()).filter(Boolean) : void 0,
      draft: r.draft === true || r.Status === "Draft"
    };
  });
}
var PARSERS = { markdown: fromMarkdown, ghost: fromGhost, notion: fromNotion };
var blog_posts_import_default = defineTool25({
  name: "blog_posts_import",
  title: "Import posts",
  description: "Import posts from Markdown (frontmatter + body; separate multiple documents with a line containing only +++), a Ghost JSON export, or a Notion JSON export. Valid posts are committed together in ONE commit; invalid or duplicate ones are reported and skipped.",
  inputSchema: {
    session_token: sessionTokenField,
    format: z15.enum(["markdown", "ghost", "notion"]).describe("Source format."),
    content: z15.string().min(1).describe("File content: Markdown text or JSON.")
  },
  annotations: { readOnlyHint: false, idempotentHint: false, openWorldHint: true },
  handler: async ({ session_token, format, content }) => ownerOperation("blog_posts_import", session_token, async (owner) => {
    let candidates;
    try {
      candidates = PARSERS[format](content);
    } catch (error) {
      throw new OperationError("IMPORT_FAILED", `Could not parse the ${format} content: ${error instanceof Error ? error.message : error}`, {
        field: "content",
        guidance: "Check that the content is a complete export in the selected format."
      });
    }
    assertBatchSize(candidates.length, "content");
    const taken = new Set((await listPostFiles(owner.token)).map((f) => f.name.replace(/\.mdx$/, "")));
    const results = [];
    const changes = [];
    for (const c of candidates) {
      let slug = "";
      try {
        slug = normalizeSlug(c.slug || c.title);
      } catch {
        results.push({ status: "failed", title: c.title, slug, reason: "No usable slug or title." });
        continue;
      }
      const date = c.date ? toDateOnly(c.date) ?? void 0 : todayDateOnly();
      const issue = collectIssues({ ...c, slug, date }, { requireAll: true })[0];
      if (issue) {
        results.push({ status: "failed", title: c.title, slug, reason: `${issue.field}: ${issue.message}` });
        continue;
      }
      if (taken.has(slug)) {
        results.push({ status: "failed", title: c.title, slug, reason: "Slug already exists." });
        continue;
      }
      taken.add(slug);
      changes.push({ path: pathForSlug(slug), content: buildMdx({ title: c.title, description: c.description, date, tags: c.tags?.slice(0, 8), draft: c.draft, readingTime: estimateReadingTime(c.body) }, c.body) });
      results.push({ status: "success", title: c.title, slug });
    }
    const commit = changes.length ? await commitFiles(owner.token, changes, `content: import ${changes.length} posts from ${format}`) : null;
    const failed = results.length - changes.length;
    return {
      data: { imported: changes.length, failed, results, commit_sha: commit?.commitSha ?? null, summary: `Imported ${changes.length} of ${results.length} posts.` },
      userMessage: `Imported ${changes.length} post${changes.length === 1 ? "" : "s"}${failed ? `; ${failed} skipped` : ""}.`
    };
  })
});

// src/lib/mcp-admin/index.ts
var mcp_admin_default = defineMcp({
  name: "somrit-webcv-admin",
  title: "Somrit Dasgupta \u2014 Site Admin",
  version: "1.1.0",
  instructions: "Owner-only authoring tools for somritdasgupta.in. Connecting requires no login. Every tool returns one envelope: success, data, error {code, message, field, guidance}, meta {operation, nextSteps}. Follow error.guidance and meta.nextSteps literally. Call mcp_schema_get when unsure which tool to use. Posts are stored with `export const frontmatter = {...}` metadata and YYYY-MM-DD dates; the server writes this format automatically. Before publishing, call blog_posts_preview, show the user the returned source, and publish only after they approve. Read tools (list, search, by_tag, stats, word_count, related, export) work without a session for published posts. For any write: call blog_auth_request once, show the user only user_code and verification_uri, then poll blog_auth_verify with the same auth_token until approved, denied, or expired. Pending is expected; keep polling, never ask the user to confirm, and never start a second authorization while seconds_remaining is positive. On approved, immediately retry the original tool with session_token, which is valid for one hour. Authorization alone never means content changed: report success only when the mutation returns published/updated/deleted true, verified true, and a commit_sha. Call blog_components_list before writing rich MDX. Call blog_posts_read before updating or deleting and pass expected_sha.",
  tools: [
    mcp_schema_get_default,
    blog_auth_request_default,
    blog_auth_verify_default,
    blog_components_list_default,
    blog_posts_suggest_slug_default,
    blog_posts_validate_default,
    blog_posts_list_default,
    blog_posts_read_default,
    blog_posts_create_default,
    blog_posts_update_default,
    blog_posts_delete_default,
    blog_posts_preview_default,
    blog_posts_search_default,
    blog_posts_by_tag_default,
    blog_posts_stats_default,
    blog_posts_word_count_default,
    blog_posts_related_default,
    blog_posts_export_default,
    blog_posts_get_draft_count_default,
    blog_posts_bulk_update_default,
    blog_posts_tag_rename_default,
    blog_posts_validate_bulk_default,
    blog_posts_duplicate_default,
    blog_posts_schedule_default,
    blog_posts_import_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_admin_default, { functionName: "mcp-admin" }));
