// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-admin
// Bundled from src/lib/mcp-admin/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-admin/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/tools/list-all-posts.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/env.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  const value = runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
  return value?.trim() || void 0;
}
function githubToken() {
  const token = runtimeEnv("GITHUB_ADMIN_TOKEN");
  if (!token) {
    throw new Error(
      "GITHUB_ADMIN_TOKEN is not configured on the server. The site owner must add it before write tools can run."
    );
  }
  return token;
}
function adminEmails() {
  return (runtimeEnv("MCP_ADMIN_EMAILS") ?? "").split(",").map((e) => e.trim().toLowerCase()).filter(Boolean);
}

// src/lib/mcp-admin/guard.ts
var NotAuthorized = class extends Error {
};
function requireAdmin(ctx) {
  if (!ctx.isAuthenticated()) {
    throw new NotAuthorized("Not signed in. Connect this server with OAuth first.");
  }
  const email = (ctx.getUserEmail() ?? "").toLowerCase();
  const userId = ctx.getUserId() ?? "";
  if (!email || !userId) {
    throw new NotAuthorized("Token carries no verified identity.");
  }
  const allowed = adminEmails();
  if (allowed.length === 0) {
    throw new NotAuthorized(
      "No admin allow-list configured on the server. Writes are disabled."
    );
  }
  if (!allowed.includes(email)) {
    throw new NotAuthorized(
      `${email} is not authorized to modify content on this site.`
    );
  }
  return { userId, email };
}
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true,
  structuredContent: { error: message }
});
async function adminTool(ctx, run) {
  try {
    const value = await run(requireAdmin(ctx));
    return {
      content: [{ type: "text", text: JSON.stringify(value, null, 2) }],
      structuredContent: value
    };
  } catch (e) {
    return errorResult(e instanceof Error ? e.message : String(e));
  }
}

// src/lib/mcp-admin/github.ts
var REPO = {
  owner: "somritdasgupta",
  name: "webCV",
  branch: "main",
  contentDir: "content/blog"
};
var API = `https://api.github.com/repos/${REPO.owner}/${REPO.name}`;
var headers = () => ({
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
  Authorization: `Bearer ${githubToken()}`,
  "User-Agent": "somrit-webcv-mcp",
  "X-GitHub-Api-Version": "2022-11-28"
});
var toB64 = (s) => {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
};
var fromB64 = (s) => {
  const bin = atob(s.replace(/\n/g, ""));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
};
async function ghFetch(url, init) {
  const res = await fetch(url, { ...init, headers: headers() });
  return res;
}
async function fail(res, action) {
  const body = await res.text();
  let message = body;
  try {
    const parsed = JSON.parse(body);
    message = parsed.message ?? body;
    if (parsed.errors) message += ` \u2014 ${JSON.stringify(parsed.errors)}`;
  } catch {
  }
  throw new Error(`${action} failed (${res.status}): ${message}`);
}
function safeSlug(input) {
  const slug = input.toLowerCase().trim().replace(/\.mdx$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
  if (!slug) throw new Error("Slug is empty after normalization.");
  return slug;
}
var pathForSlug = (slug) => `${REPO.contentDir}/${slug}.mdx`;
async function listPostFiles() {
  const res = await ghFetch(
    `${API}/contents/${REPO.contentDir}?ref=${REPO.branch}`
  );
  if (res.status === 404) return [];
  if (!res.ok) await fail(res, "List posts");
  const data = await res.json();
  return data.filter((f) => f.type === "file" && f.name.endsWith(".mdx")).map(({ name, path, sha }) => ({ name, path, sha }));
}
async function readFile(path) {
  const res = await ghFetch(
    `${API}/contents/${encodeURI(path)}?ref=${REPO.branch}`
  );
  if (res.status === 404) return null;
  if (!res.ok) await fail(res, "Read file");
  const data = await res.json();
  return { content: fromB64(data.content), sha: data.sha };
}
async function writeFile(opts) {
  const res = await ghFetch(`${API}/contents/${encodeURI(opts.path)}`, {
    method: "PUT",
    body: JSON.stringify({
      message: opts.message,
      content: toB64(opts.content),
      branch: REPO.branch,
      ...opts.sha ? { sha: opts.sha } : {}
    })
  });
  if (!res.ok) await fail(res, "Commit");
  const data = await res.json();
  return {
    commitSha: data.commit.sha,
    fileSha: data.content.sha,
    htmlUrl: data.content.html_url
  };
}
async function deleteFile(opts) {
  const res = await ghFetch(`${API}/contents/${encodeURI(opts.path)}`, {
    method: "DELETE",
    body: JSON.stringify({
      message: opts.message,
      sha: opts.sha,
      branch: REPO.branch
    })
  });
  if (!res.ok) await fail(res, "Delete");
  const data = await res.json();
  return { commitSha: data.commit.sha };
}

// src/lib/mcp-admin/mdx.ts
var quote = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
function buildMdx(fm, body) {
  const lines = [
    "---",
    `title: ${quote(fm.title)}`,
    `description: ${quote(fm.description)}`,
    `date: ${quote(fm.date)}`
  ];
  if (fm.tags?.length) lines.push(`tags: [${fm.tags.map(quote).join(", ")}]`);
  if (fm.cover) lines.push(`cover: ${quote(fm.cover)}`);
  if (typeof fm.readingTime === "number") lines.push(`readingTime: ${fm.readingTime}`);
  if (fm.draft) lines.push("draft: true");
  lines.push("---", "");
  return `${lines.join("\n")}
${body.replace(/^\n+/, "").trimEnd()}
`;
}
function parseFrontmatter(src) {
  const match = src.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  if (!match) return { data: {}, body: src };
  const data = {};
  for (const line of match[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    const value = rawValue.trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value.slice(1, -1).split(",").map((v) => v.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
    } else if (value === "true" || value === "false") {
      data[key] = value === "true";
    } else {
      data[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return { data, body: src.slice(match[0].length) };
}
function estimateReadingTime(body) {
  const words = body.replace(/```[\s\S]*?```/g, " ").replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 220));
}

// src/lib/mcp-admin/tools/list-all-posts.ts
var list_all_posts_default = defineTool({
  name: "list_all_posts",
  title: "List all posts (including drafts)",
  description: "List every MDX post in the content repository, including drafts and future-dated (scheduled) posts that the public site hides. Requires admin sign-in.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: (_input, ctx) => adminTool(ctx, async () => {
    const files = await listPostFiles();
    const posts = await Promise.all(
      files.map(async (f) => {
        const file = await readFile(f.path);
        const { data } = parseFrontmatter(file?.content ?? "");
        const slug = f.name.replace(/\.mdx$/, "");
        const date = String(data.date ?? "");
        return {
          slug,
          path: f.path,
          sha: f.sha,
          title: String(data.title ?? slug),
          description: String(data.description ?? ""),
          date,
          tags: Array.isArray(data.tags) ? data.tags : [],
          draft: data.draft === true,
          scheduled: Boolean(date) && new Date(date).getTime() > Date.now()
        };
      })
    );
    posts.sort((a, b) => (b.date || "").localeCompare(a.date || ""));
    return { count: posts.length, posts };
  })
});

// src/lib/mcp-admin/tools/read-post-source.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var read_post_source_default = defineTool2({
  name: "read_post_source",
  title: "Read post source",
  description: "Read the raw MDX source, parsed frontmatter, and current blob SHA of a post \u2014 including drafts. The SHA is required to update or delete the post safely.",
  inputSchema: {
    slug: z.string().min(1).describe("Post slug, e.g. 'hello-world'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ slug }, ctx) => adminTool(ctx, async () => {
    const clean = safeSlug(slug);
    const path = pathForSlug(clean);
    const file = await readFile(path);
    if (!file) throw new Error(`Post not found: ${clean}`);
    const { data, body } = parseFrontmatter(file.content);
    return {
      slug: clean,
      path,
      sha: file.sha,
      frontmatter: data,
      body,
      source: file.content
    };
  })
});

// src/lib/mcp-admin/tools/create-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var create_post_default = defineTool3({
  name: "create_post",
  title: "Create blog post",
  description: "Create a new MDX blog post and commit it to the content repository. Fails if the slug already exists \u2014 use update_post to change an existing post. Set a future date to schedule, or draft to keep it hidden.",
  inputSchema: {
    slug: z2.string().min(1).describe("URL slug, e.g. 'why-rust-wins'. Normalized to lowercase kebab-case."),
    title: z2.string().trim().min(1).max(120).describe("Post title."),
    description: z2.string().trim().min(1).max(160).describe("Meta description, kept under 160 characters for SEO."),
    body: z2.string().min(1).describe("Post body in MDX (no frontmatter \u2014 it is generated for you)."),
    date: z2.string().optional().describe("ISO 8601 publish date. Defaults to now. A future date schedules the post."),
    tags: z2.array(z2.string().trim().min(1)).max(8).optional().describe("Topic tags."),
    cover: z2.string().url().optional().describe("Absolute cover image URL."),
    draft: z2.boolean().optional().describe("Keep the post hidden from the public site when true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: (input, ctx) => adminTool(ctx, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    if (await readFile(path)) {
      throw new Error(
        `Post '${slug}' already exists. Use update_post to modify it, or pick another slug.`
      );
    }
    const date = input.date ? new Date(input.date) : /* @__PURE__ */ new Date();
    if (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${input.date}`);
    const mdx = buildMdx(
      {
        title: input.title,
        description: input.description,
        date: date.toISOString(),
        tags: input.tags,
        cover: input.cover,
        draft: input.draft,
        readingTime: estimateReadingTime(input.body)
      },
      input.body
    );
    const result = await writeFile({
      path,
      content: mdx,
      message: `content: add "${input.title}" (via MCP by ${admin.email})`
    });
    return {
      slug,
      path,
      url: `https://somritdasgupta.in/blog/${slug}`,
      scheduled: date.getTime() > Date.now(),
      draft: input.draft === true,
      ...result
    };
  })
});

// src/lib/mcp-admin/tools/update-post.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var update_post_default = defineTool4({
  name: "update_post",
  title: "Update blog post",
  description: "Update an existing MDX post. Only the fields you pass are changed; everything else is preserved. Pass expected_sha from read_post_source to guard against overwriting concurrent edits.",
  inputSchema: {
    slug: z3.string().min(1).describe("Slug of the post to update."),
    title: z3.string().trim().min(1).max(120).optional(),
    description: z3.string().trim().min(1).max(160).optional(),
    body: z3.string().min(1).optional().describe("Replacement MDX body (without frontmatter)."),
    date: z3.string().optional().describe("New ISO 8601 publish date."),
    tags: z3.array(z3.string().trim().min(1)).max(8).optional(),
    cover: z3.string().url().optional(),
    draft: z3.boolean().optional().describe("Toggle draft visibility."),
    expected_sha: z3.string().optional().describe("Blob SHA from read_post_source. Rejects the write if the file changed since.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: (input, ctx) => adminTool(ctx, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    const file = await readFile(path);
    if (!file) throw new Error(`Post not found: ${slug}. Use create_post instead.`);
    if (input.expected_sha && input.expected_sha !== file.sha) {
      throw new Error(
        `Stale write rejected: the post changed since you read it (expected ${input.expected_sha}, found ${file.sha}). Re-read it and retry.`
      );
    }
    const { data, body: currentBody } = parseFrontmatter(file.content);
    const body = input.body ?? currentBody;
    const rawDate = input.date ?? String(data.date ?? (/* @__PURE__ */ new Date()).toISOString());
    const date = new Date(rawDate);
    if (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${rawDate}`);
    const draft = input.draft ?? data.draft === true;
    const mdx = buildMdx(
      {
        title: input.title ?? String(data.title ?? slug),
        description: input.description ?? String(data.description ?? ""),
        date: date.toISOString(),
        tags: input.tags ?? (Array.isArray(data.tags) ? data.tags : void 0),
        cover: input.cover ?? (data.cover ? String(data.cover) : void 0),
        draft,
        readingTime: estimateReadingTime(body)
      },
      body
    );
    if (mdx === file.content) {
      return { slug, path, changed: false, message: "No changes to commit." };
    }
    const result = await writeFile({
      path,
      content: mdx,
      sha: file.sha,
      message: `content: update "${slug}" (via MCP by ${admin.email})`
    });
    return {
      slug,
      path,
      changed: true,
      url: `https://somritdasgupta.in/blog/${slug}`,
      scheduled: date.getTime() > Date.now(),
      draft,
      ...result
    };
  })
});

// src/lib/mcp-admin/tools/delete-post.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var delete_post_default = defineTool5({
  name: "delete_post",
  title: "Delete blog post",
  description: "Permanently delete a published MDX post from the content repository. Requires confirm: true, so a model cannot delete a post by accident. Prefer update_post with draft: true to unpublish without losing content.",
  inputSchema: {
    slug: z4.string().min(1).describe("Slug of the post to delete."),
    confirm: z4.literal(true).describe("Must be true. Explicit acknowledgement that the file will be removed."),
    expected_sha: z4.string().optional().describe("Blob SHA from read_post_source. Rejects the delete if the file changed since.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: true },
  handler: (input, ctx) => adminTool(ctx, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    const file = await readFile(path);
    if (!file) throw new Error(`Post not found: ${slug}. Nothing was deleted.`);
    if (input.expected_sha && input.expected_sha !== file.sha) {
      throw new Error(
        `Stale delete rejected: the post changed since you read it (expected ${input.expected_sha}, found ${file.sha}).`
      );
    }
    const { data } = parseFrontmatter(file.content);
    const { commitSha } = await deleteFile({
      path,
      sha: file.sha,
      message: `content: delete "${slug}" (via MCP by ${admin.email})`
    });
    return {
      slug,
      path,
      deleted: true,
      title: String(data.title ?? slug),
      commitSha
    };
  })
});

// src/lib/mcp-admin/index.ts
var projectRef = "mrbhitfbyqddejzuraim";
var mcp_admin_default = defineMcp({
  name: "somrit-webcv-admin",
  title: "Somrit Dasgupta \u2014 Site Admin",
  version: "0.1.0",
  instructions: "Authoring tools for somritdasgupta.in. Create, update, and delete MDX blog posts in the site's content repository. Every call requires an OAuth sign-in and the signed-in account must be on the site owner's admin allow-list. Read a post with read_post_source before updating or deleting it, and pass the returned expected_sha so concurrent edits are never silently overwritten.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_all_posts_default, read_post_source_default, create_post_default, update_post_default, delete_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_admin_default, { functionName: "mcp-admin" }));
