// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp-admin
// Bundled from src/lib/mcp-admin/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp-admin/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/tools/authenticate-for-blog-posting.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp-admin/env.ts
function runtimeEnv(name) {
  const runtime = globalThis;
  const value = runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
  return value?.trim() || void 0;
}
function authEncryptionKey() {
  const key = runtimeEnv("MCP_AUTH_ENCRYPTION_KEY");
  if (!key) throw new Error("MCP authoring authentication is not configured.");
  return key;
}

// src/lib/mcp-admin/github-device-auth.ts
var GITHUB_CLIENT_ID = "Ov23li98oVkx9PDOvktP";
var ADMIN_LOGIN = "somritdasgupta";
var SESSION_TTL_MS = 60 * 60 * 1e3;
var APPROVAL_WINDOW_SECONDS = 180;
var MAX_LONG_POLL_MS = 2e4;
var encoder = new TextEncoder();
var decoder = new TextDecoder();
var bytesToBase64Url = (bytes) => {
  let binary = "";
  for (const byte of bytes) binary += String.fromCharCode(byte);
  return btoa(binary).replace(/\+/g, "-").replace(/\//g, "_").replace(/=+$/, "");
};
var base64UrlToBytes = (value) => {
  const padded = value.replace(/-/g, "+").replace(/_/g, "/").padEnd(Math.ceil(value.length / 4) * 4, "=");
  return Uint8Array.from(atob(padded), (character) => character.charCodeAt(0));
};
var sleep = (ms) => new Promise((resolve) => setTimeout(resolve, ms));
async function encryptionKey() {
  const digest = await crypto.subtle.digest("SHA-256", encoder.encode(authEncryptionKey()));
  return crypto.subtle.importKey("raw", digest, "AES-GCM", false, ["encrypt", "decrypt"]);
}
async function seal(payload) {
  const iv = crypto.getRandomValues(new Uint8Array(12));
  const ciphertext = await crypto.subtle.encrypt(
    { name: "AES-GCM", iv },
    await encryptionKey(),
    encoder.encode(JSON.stringify(payload))
  );
  return `${bytesToBase64Url(iv)}.${bytesToBase64Url(new Uint8Array(ciphertext))}`;
}
async function unseal(handle) {
  const [ivValue, ciphertextValue] = handle.split(".");
  if (!ivValue || !ciphertextValue) throw new Error("Invalid or expired authorization handle. Run authenticate_for_blog_posting again.");
  try {
    const plaintext = await crypto.subtle.decrypt(
      { name: "AES-GCM", iv: base64UrlToBytes(ivValue) },
      await encryptionKey(),
      base64UrlToBytes(ciphertextValue)
    );
    return JSON.parse(decoder.decode(plaintext));
  } catch {
    throw new Error("Invalid or expired authorization handle. Run authenticate_for_blog_posting again.");
  }
}
async function createAuthorization() {
  const response = await fetch("https://github.com/login/device/code", {
    method: "POST",
    headers: { Accept: "application/json", "Content-Type": "application/json" },
    body: JSON.stringify({ client_id: GITHUB_CLIENT_ID, scope: "repo" })
  });
  if (!response.ok) throw new Error(`GitHub authorization failed (${response.status}).`);
  const data = await response.json();
  const deviceCode = String(data.device_code ?? "");
  if (!deviceCode) throw new Error("GitHub did not return an authorization request.");
  const interval = Math.max(Number(data.interval ?? 5), 2);
  const expiresIn = Math.min(Number(data.expires_in ?? APPROVAL_WINDOW_SECONDS), APPROVAL_WINDOW_SECONDS);
  const expiresAt = Date.now() + expiresIn * 1e3;
  return {
    authorizationRequest: await seal({ purpose: "github-device", deviceCode, expiresAt, interval }),
    userCode: String(data.user_code ?? ""),
    verificationUri: String(data.verification_uri ?? "https://github.com/login/device"),
    expiresIn,
    pollUntil: new Date(expiresAt).toISOString(),
    interval
  };
}
async function exchangeDeviceCode(deviceCode) {
  const response = await fetch("https://github.com/login/oauth/access_token", {
    method: "POST",
    headers: { Accept: "application/json", "Content-Type": "application/json" },
    body: JSON.stringify({
      client_id: GITHUB_CLIENT_ID,
      device_code: deviceCode,
      grant_type: "urn:ietf:params:oauth:grant-type:device_code"
    })
  });
  const data = await response.json();
  if (data.access_token) return { state: "approved", token: String(data.access_token) };
  const error = String(data.error ?? "authorization_pending");
  const detail = String(data.error_description ?? error);
  if (error === "authorization_pending" || error === "slow_down") return { state: "pending" };
  if (error === "expired_token") return { state: "expired", detail: "The approval window closed before GitHub confirmed it." };
  return { state: "denied", detail };
}
async function githubUser(token) {
  const response = await fetch("https://api.github.com/user", {
    headers: { Accept: "application/vnd.github+json", Authorization: `Bearer ${token}` }
  });
  if (!response.ok) throw new Error(`GitHub identity check failed (${response.status}).`);
  return response.json();
}
var secondsLeft = (expiresAt) => Math.max(0, Math.round((expiresAt - Date.now()) / 1e3));
async function pollAuthorization(authorizationRequest) {
  const request = await unseal(authorizationRequest);
  if (request.purpose !== "github-device" || !request.deviceCode) {
    throw new Error("Invalid authorization request. Call authenticate_for_blog_posting once and reuse its authorization_request.");
  }
  const deadline = Math.min(Date.now() + MAX_LONG_POLL_MS, request.expiresAt);
  const intervalMs = Math.max(request.interval, 2) * 1e3;
  for (; ; ) {
    if (Date.now() >= request.expiresAt) {
      return { status: "expired", ownerSession: null, timeRemaining: 0, detail: "The approval window closed. Start authentication once more." };
    }
    const result = await exchangeDeviceCode(request.deviceCode);
    if (result.state === "approved") {
      const user = await githubUser(result.token);
      if (user.login.toLowerCase() !== ADMIN_LOGIN) {
        return { status: "denied", ownerSession: null, timeRemaining: 0, detail: `Signed in as ${user.login}. Only ${ADMIN_LOGIN} can author posts.` };
      }
      const ownerSession = await seal({ purpose: "owner-session", token: result.token, login: user.login, expiresAt: Date.now() + SESSION_TTL_MS });
      return { status: "approved", ownerSession, timeRemaining: 0, detail: "Owner verified. Resume the pending authoring request now." };
    }
    if (result.state === "denied" || result.state === "expired") {
      return { status: result.state, ownerSession: null, timeRemaining: secondsLeft(request.expiresAt), detail: result.detail };
    }
    if (Date.now() + intervalMs >= deadline) {
      return {
        status: "pending",
        ownerSession: null,
        timeRemaining: secondsLeft(request.expiresAt),
        detail: "Waiting for GitHub approval. Call check_auth_status again with the same authorization_request."
      };
    }
    await sleep(intervalMs);
  }
}
async function authorizedGitHub(handle) {
  const session = await unseal(handle);
  if (session.purpose !== "owner-session") throw new Error("Invalid owner session.");
  if (session.expiresAt <= Date.now()) throw new Error("Authorization expired. Run authenticate_for_blog_posting again.");
  if (session.login.toLowerCase() !== ADMIN_LOGIN) throw new Error("This GitHub account cannot publish.");
  return { token: session.token, login: session.login };
}

// src/lib/mcp-admin/tools/authenticate-for-blog-posting.ts
var authenticate_for_blog_posting_default = defineTool({
  name: "authenticate_for_blog_posting",
  title: "Authenticate for blog posting",
  description: "Start owner verification for any authoring action. Call this automatically when no owner_session is active, keep the pending authoring request in memory, show the user_code with a live countdown of expires_in, then poll check_auth_status with the returned authorization_request until it reports approved. Never ask the user to confirm manually and never start a second authentication while the first is valid.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async () => {
    const authorization = await createAuthorization();
    return {
      content: [{
        type: "text",
        text: `Owner approval required. Show the user: open ${authorization.verificationUri} and enter code ${authorization.userCode}. Display a countdown from ${authorization.expiresIn} seconds. Immediately begin polling check_auth_status with the authorization_request from structuredContent until it returns approved, then resume the preserved authoring request. Do not ask the user to confirm approval.`
      }],
      structuredContent: {
        user_code: authorization.userCode,
        verification_uri: authorization.verificationUri,
        authorization_request: authorization.authorizationRequest,
        expires_in: authorization.expiresIn,
        poll_until: authorization.pollUntil,
        interval: authorization.interval,
        owner_session: null
      }
    };
  }
});

// src/lib/mcp-admin/tools/check-auth-status.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var check_auth_status_default = defineTool2({
  name: "check_auth_status",
  title: "Check authorization status",
  description: "Poll the pending GitHub approval. Blocks briefly while waiting, so call it repeatedly with the same authorization_request until status is approved, denied, or expired. Pending is not an error. On approved, pass owner_session straight into the preserved authoring tool.",
  inputSchema: {
    authorization_request: z.string().min(20).describe("Opaque authorization_request from authenticate_for_blog_posting. Never the user-facing code.")
  },
  annotations: { readOnlyHint: true, idempotentHint: false, openWorldHint: true },
  handler: async ({ authorization_request }) => {
    try {
      const status = await pollAuthorization(authorization_request);
      return {
        content: [{ type: "text", text: status.detail }],
        structuredContent: {
          status: status.status,
          owner_session: status.ownerSession,
          time_remaining: status.timeRemaining,
          authorization_request: status.status === "pending" ? authorization_request : void 0,
          detail: status.detail
        }
      };
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      return { content: [{ type: "text", text: message }], structuredContent: { status: "expired", owner_session: null, time_remaining: 0, detail: message }, isError: true };
    }
  }
});

// src/lib/mcp-admin/tools/list-all-posts.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/guard.ts
var errorResult = (message) => ({
  content: [{ type: "text", text: message }],
  isError: true,
  structuredContent: { error: message }
});
async function adminTool(ownerSession, run) {
  try {
    const value = await run(await authorizedGitHub(ownerSession));
    return {
      content: [{ type: "text", text: JSON.stringify(value, null, 2) }],
      structuredContent: value
    };
  } catch (e) {
    return errorResult(e instanceof Error ? e.message : String(e));
  }
}

// src/lib/mcp-admin/github.ts
var REPO = {
  owner: "somritdasgupta",
  name: "webCV",
  branch: "main",
  contentDir: "content/blog"
};
var API = `https://api.github.com/repos/${REPO.owner}/${REPO.name}`;
var headers = (token) => ({
  Accept: "application/vnd.github+json",
  "Content-Type": "application/json",
  Authorization: `Bearer ${token}`,
  "User-Agent": "somrit-webcv-mcp",
  "X-GitHub-Api-Version": "2022-11-28"
});
var toB64 = (s) => {
  const bytes = new TextEncoder().encode(s);
  let bin = "";
  for (const b of bytes) bin += String.fromCharCode(b);
  return btoa(bin);
};
var fromB64 = (s) => {
  const bin = atob(s.replace(/\n/g, ""));
  return new TextDecoder().decode(Uint8Array.from(bin, (c) => c.charCodeAt(0)));
};
async function ghFetch(token, url, init) {
  const res = await fetch(url, { ...init, headers: headers(token) });
  return res;
}
async function fail(res, action) {
  const body = await res.text();
  let message = body;
  try {
    const parsed = JSON.parse(body);
    message = parsed.message ?? body;
    if (parsed.errors) message += ` \u2014 ${JSON.stringify(parsed.errors)}`;
  } catch {
  }
  throw new Error(`${action} failed (${res.status}): ${message}`);
}
function safeSlug(input) {
  const slug = input.toLowerCase().trim().replace(/\.mdx$/, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "").slice(0, 80);
  if (!slug) throw new Error("Slug is empty after normalization.");
  return slug;
}
var pathForSlug = (slug) => `${REPO.contentDir}/${slug}.mdx`;
async function listPostFiles(token) {
  const res = await ghFetch(
    token,
    `${API}/contents/${REPO.contentDir}?ref=${REPO.branch}`
  );
  if (res.status === 404) return [];
  if (!res.ok) await fail(res, "List posts");
  const data = await res.json();
  return data.filter((f) => f.type === "file" && f.name.endsWith(".mdx")).map(({ name, path, sha }) => ({ name, path, sha }));
}
async function readFile(token, path) {
  const res = await ghFetch(
    token,
    `${API}/contents/${encodeURI(path)}?ref=${REPO.branch}`
  );
  if (res.status === 404) return null;
  if (!res.ok) await fail(res, "Read file");
  const data = await res.json();
  return { content: fromB64(data.content), sha: data.sha };
}
async function writeFile(opts) {
  const res = await ghFetch(opts.token, `${API}/contents/${encodeURI(opts.path)}`, {
    method: "PUT",
    body: JSON.stringify({
      message: opts.message,
      content: toB64(opts.content),
      branch: REPO.branch,
      ...opts.sha ? { sha: opts.sha } : {}
    })
  });
  if (!res.ok) await fail(res, "Commit");
  const data = await res.json();
  return {
    commitSha: data.commit.sha,
    fileSha: data.content.sha,
    htmlUrl: data.content.html_url
  };
}
async function deleteFile(opts) {
  const res = await ghFetch(opts.token, `${API}/contents/${encodeURI(opts.path)}`, {
    method: "DELETE",
    body: JSON.stringify({
      message: opts.message,
      sha: opts.sha,
      branch: REPO.branch
    })
  });
  if (!res.ok) await fail(res, "Delete");
  const data = await res.json();
  return { commitSha: data.commit.sha };
}

// src/lib/mcp-admin/mdx.ts
var quote = (s) => `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
function buildMdx(fm, body) {
  const lines = [
    "---",
    `title: ${quote(fm.title)}`,
    `description: ${quote(fm.description)}`,
    `date: ${quote(fm.date)}`
  ];
  if (fm.tags?.length) lines.push(`tags: [${fm.tags.map(quote).join(", ")}]`);
  if (fm.cover) lines.push(`cover: ${quote(fm.cover)}`);
  if (typeof fm.readingTime === "number") lines.push(`readingTime: ${fm.readingTime}`);
  if (fm.draft) lines.push("draft: true");
  lines.push("---", "");
  return `${lines.join("\n")}
${body.replace(/^\n+/, "").trimEnd()}
`;
}
function parseFrontmatter(src) {
  const match = src.match(/^---\s*\n([\s\S]*?)\n---\s*\n?/);
  if (!match) return { data: {}, body: src };
  const data = {};
  for (const line of match[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    const [, key, rawValue] = kv;
    const value = rawValue.trim();
    if (value.startsWith("[") && value.endsWith("]")) {
      data[key] = value.slice(1, -1).split(",").map((v) => v.trim().replace(/^["']|["']$/g, "")).filter(Boolean);
    } else if (value === "true" || value === "false") {
      data[key] = value === "true";
    } else {
      data[key] = value.replace(/^["']|["']$/g, "");
    }
  }
  return { data, body: src.slice(match[0].length) };
}
function estimateReadingTime(body) {
  const words = body.replace(/```[\s\S]*?```/g, " ").replace(/<[^>]+>/g, " ").split(/\s+/).filter(Boolean).length;
  return Math.max(1, Math.round(words / 220));
}

// src/lib/mcp-admin/tools/list-all-posts.ts
var list_all_posts_default = defineTool3({
  name: "list_all_posts",
  title: "List all posts (including drafts)",
  description: "List every MDX post in the content repository, including drafts and future-dated (scheduled) posts that the public site hides. Requires admin sign-in.",
  inputSchema: {
    owner_session: z2.string().min(1).describe("One-hour owner session returned by check_auth_status.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: (input) => adminTool(input.owner_session, async (admin) => {
    const files = await listPostFiles(admin.token);
    const posts = await Promise.all(
      files.map(async (f) => {
        const file = await readFile(admin.token, f.path);
        const { data } = parseFrontmatter(file?.content ?? "");
        const slug = f.name.replace(/\.mdx$/, "");
        const date = String(data.date ?? "");
        return {
          slug,
          path: f.path,
          sha: f.sha,
          title: String(data.title ?? slug),
          description: String(data.description ?? ""),
          date,
          tags: Array.isArray(data.tags) ? data.tags : [],
          draft: data.draft === true,
          scheduled: Boolean(date) && new Date(date).getTime() > Date.now()
        };
      })
    );
    posts.sort((a, b) => (b.date || "").localeCompare(a.date || ""));
    return { count: posts.length, posts };
  })
});

// src/lib/mcp-admin/tools/read-post-source.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var read_post_source_default = defineTool4({
  name: "read_post_source",
  title: "Read post source",
  description: "Read the raw MDX source, parsed frontmatter, and current blob SHA of a post \u2014 including drafts. The SHA is required to update or delete the post safely.",
  inputSchema: {
    owner_session: z3.string().min(1).describe("One-hour owner session returned by check_auth_status."),
    slug: z3.string().min(1).describe("Post slug, e.g. 'hello-world'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: ({ slug, owner_session }) => adminTool(owner_session, async (admin) => {
    const clean = safeSlug(slug);
    const path = pathForSlug(clean);
    const file = await readFile(admin.token, path);
    if (!file) throw new Error(`Post not found: ${clean}`);
    const { data, body } = parseFrontmatter(file.content);
    return {
      slug: clean,
      path,
      sha: file.sha,
      frontmatter: data,
      body,
      source: file.content
    };
  })
});

// src/lib/mcp-admin/tools/create-post.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var create_post_default = defineTool5({
  name: "create_post",
  title: "Create blog post",
  description: "Create and publish a new MDX blog post, then read the committed file back from GitHub before returning success. Use owner_session from check_auth_status; if none is active, call authenticate_for_blog_posting, preserve this complete request, and poll until approved. Use get_mdx_components for rich MDX. Fails if the slug exists; set a future date to schedule or draft to hide it.",
  inputSchema: {
    owner_session: z4.string().min(1).describe("One-hour owner session returned by check_auth_status. This is an opaque workflow value, not a GitHub token."),
    slug: z4.string().min(1).describe("URL slug, e.g. 'why-rust-wins'. Normalized to lowercase kebab-case."),
    title: z4.string().trim().min(1).max(120).describe("Post title."),
    description: z4.string().trim().min(1).max(160).describe("Meta description, kept under 160 characters for SEO."),
    body: z4.string().min(1).describe("Complete post body in Markdown/MDX, without frontmatter. Custom components returned by get_mdx_components are supported."),
    date: z4.string().optional().describe("ISO 8601 publish date. Defaults to now. A future date schedules the post."),
    tags: z4.array(z4.string().trim().min(1)).max(8).optional().describe("Topic tags."),
    cover: z4.string().url().optional().describe("Absolute cover image URL."),
    draft: z4.boolean().optional().describe("Keep the post hidden from the public site when true.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: (input) => adminTool(input.owner_session, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    if (await readFile(admin.token, path)) {
      throw new Error(
        `Post '${slug}' already exists. Use update_post to modify it, or pick another slug.`
      );
    }
    const date = input.date ? new Date(input.date) : /* @__PURE__ */ new Date();
    if (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${input.date}`);
    const mdx = buildMdx(
      {
        title: input.title,
        description: input.description,
        date: date.toISOString(),
        tags: input.tags,
        cover: input.cover,
        draft: input.draft,
        readingTime: estimateReadingTime(input.body)
      },
      input.body
    );
    const result = await writeFile({
      token: admin.token,
      path,
      content: mdx,
      message: `content: add "${input.title}" (via MCP by ${admin.login})`
    });
    const committed = await readFile(admin.token, path);
    if (!committed || committed.sha !== result.fileSha || committed.content !== mdx) {
      throw new Error("GitHub accepted the write but commit verification failed. Publishing was not confirmed; check the repository before retrying.");
    }
    return {
      published: true,
      verified: true,
      slug,
      path,
      url: `https://somritdasgupta.in/blog/${slug}`,
      scheduled: date.getTime() > Date.now(),
      draft: input.draft === true,
      ...result,
      message: `Published and verified commit ${result.commitSha}.`
    };
  })
});

// src/lib/mcp-admin/tools/update-post.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z5 } from "npm:zod@^3.25.76";
var update_post_default = defineTool6({
  name: "update_post",
  title: "Update blog post",
  description: "Update an existing MDX post. Only the fields you pass are changed; everything else is preserved. Pass expected_sha from read_post_source to guard against overwriting concurrent edits.",
  inputSchema: {
    owner_session: z5.string().min(1).describe("One-hour owner session returned by check_auth_status. This is an opaque workflow value, not a GitHub token."),
    slug: z5.string().min(1).describe("Slug of the post to update."),
    title: z5.string().trim().min(1).max(120).optional(),
    description: z5.string().trim().min(1).max(160).optional(),
    body: z5.string().min(1).optional().describe("Replacement MDX body (without frontmatter)."),
    date: z5.string().optional().describe("New ISO 8601 publish date."),
    tags: z5.array(z5.string().trim().min(1)).max(8).optional(),
    cover: z5.string().url().optional(),
    draft: z5.boolean().optional().describe("Toggle draft visibility."),
    expected_sha: z5.string().optional().describe("Blob SHA from read_post_source. Rejects the write if the file changed since.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: true },
  handler: (input) => adminTool(input.owner_session, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    const file = await readFile(admin.token, path);
    if (!file) throw new Error(`Post not found: ${slug}. Use create_post instead.`);
    if (input.expected_sha && input.expected_sha !== file.sha) {
      throw new Error(
        `Stale write rejected: the post changed since you read it (expected ${input.expected_sha}, found ${file.sha}). Re-read it and retry.`
      );
    }
    const { data, body: currentBody } = parseFrontmatter(file.content);
    const body = input.body ?? currentBody;
    const rawDate = input.date ?? String(data.date ?? (/* @__PURE__ */ new Date()).toISOString());
    const date = new Date(rawDate);
    if (Number.isNaN(date.getTime())) throw new Error(`Invalid date: ${rawDate}`);
    const draft = input.draft ?? data.draft === true;
    const mdx = buildMdx(
      {
        title: input.title ?? String(data.title ?? slug),
        description: input.description ?? String(data.description ?? ""),
        date: date.toISOString(),
        tags: input.tags ?? (Array.isArray(data.tags) ? data.tags : void 0),
        cover: input.cover ?? (data.cover ? String(data.cover) : void 0),
        draft,
        readingTime: estimateReadingTime(body)
      },
      body
    );
    if (mdx === file.content) {
      return { slug, path, changed: false, message: "No changes to commit." };
    }
    const result = await writeFile({
      token: admin.token,
      path,
      content: mdx,
      sha: file.sha,
      message: `content: update "${slug}" (via MCP by ${admin.login})`
    });
    const committed = await readFile(admin.token, path);
    if (!committed || committed.sha !== result.fileSha || committed.content !== mdx) {
      throw new Error("GitHub accepted the update but commit verification failed. The update was not confirmed; check the repository before retrying.");
    }
    return {
      updated: true,
      slug,
      path,
      changed: true,
      url: `https://somritdasgupta.in/blog/${slug}`,
      scheduled: date.getTime() > Date.now(),
      draft,
      ...result,
      verified: true,
      message: `Updated and verified commit ${result.commitSha}.`
    };
  })
});

// src/lib/mcp-admin/tools/delete-post.ts
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z6 } from "npm:zod@^3.25.76";
var delete_post_default = defineTool7({
  name: "delete_post",
  title: "Delete blog post",
  description: "Permanently delete a published MDX post from the content repository. Requires confirm: true, so a model cannot delete a post by accident. Prefer update_post with draft: true to unpublish without losing content.",
  inputSchema: {
    owner_session: z6.string().min(1).describe("One-hour owner session returned by check_auth_status. This is an opaque workflow value, not a GitHub token."),
    slug: z6.string().min(1).describe("Slug of the post to delete."),
    confirm: z6.literal(true).describe("Must be true. Explicit acknowledgement that the file will be removed."),
    expected_sha: z6.string().optional().describe("Blob SHA from read_post_source. Rejects the delete if the file changed since.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, openWorldHint: true },
  handler: (input) => adminTool(input.owner_session, async (admin) => {
    const slug = safeSlug(input.slug);
    const path = pathForSlug(slug);
    const file = await readFile(admin.token, path);
    if (!file) throw new Error(`Post not found: ${slug}. Nothing was deleted.`);
    if (input.expected_sha && input.expected_sha !== file.sha) {
      throw new Error(
        `Stale delete rejected: the post changed since you read it (expected ${input.expected_sha}, found ${file.sha}).`
      );
    }
    const { data } = parseFrontmatter(file.content);
    const { commitSha } = await deleteFile({
      token: admin.token,
      path,
      sha: file.sha,
      message: `content: delete "${slug}" (via MCP by ${admin.login})`
    });
    if (await readFile(admin.token, path)) {
      throw new Error("GitHub accepted the delete but the file still exists. Deletion was not confirmed.");
    }
    return {
      slug,
      path,
      deleted: true,
      title: String(data.title ?? slug),
      commitSha,
      verified: true,
      message: `Deleted and verified commit ${commitSha}.`
    };
  })
});

// src/lib/mcp-admin/tools/get-mdx-components.ts
import { defineTool as defineTool8 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z7 } from "npm:zod@^3.25.76";

// src/lib/mcp-admin/mdx-components.ts
var MDX_COMPONENTS = [
  { name: "Callout", purpose: "Emphasize a note, tip, warning, danger, or success message.", example: '<Callout type="tip" title="Key idea">\nUseful context.\n</Callout>' },
  { name: "ProsCons", purpose: "Compare benefits and drawbacks in two columns.", example: '<ProsCons pros={["Fast", "Simple"]} cons={["Limited"]} />' },
  { name: "Quote", purpose: "Render a prominent quotation with attribution.", example: '<Quote author="Author">\nQuoted text.\n</Quote>' },
  { name: "Kbd", purpose: "Render an inline keyboard key.", example: "<Kbd>Cmd</Kbd> + <Kbd>K</Kbd>" },
  { name: "LiveCode", purpose: "Add an editable React playground.", example: '<LiveCode template="react" files={{ "/App.js": `export default () => <h2>Hello</h2>` }} />' },
  { name: "Tweet", purpose: "Embed a post from X by ID.", example: '<Tweet id="1683920951807971329" />' },
  { name: "Chart", purpose: "Render line, bar, area, pie, or radar data.", example: '<Chart type="line" title="Users" data={[{ week: "W1", users: 120 }, { week: "W2", users: 180 }]} />' },
  { name: "Stats", purpose: "Show a compact grid of metrics.", example: '<Stats cols={2} items={[{ label: "Posts", value: "42", change: 8 }]} />' },
  { name: "Tabs", purpose: "Group related content into tabs.", example: '<Tabs>\n  <Tab label="npm">`npm install pkg`</Tab>\n  <Tab label="bun">`bun add pkg`</Tab>\n</Tabs>' },
  { name: "Steps", purpose: "Present a numbered walkthrough.", example: '<Steps>\n  <Step title="Install">Run the command.</Step>\n  <Step title="Configure">Set the variables.</Step>\n</Steps>' },
  { name: "Accordion", purpose: "Add collapsible sections or FAQs.", example: '<Accordion>\n  <AccordionItem title="Question?">Answer.</AccordionItem>\n</Accordion>' },
  { name: "Video", purpose: "Embed YouTube or a direct video file.", example: '<Video src="https://www.youtube.com/watch?v=VIDEO_ID" caption="Caption" />' },
  { name: "Badge", purpose: "Render an inline status label.", example: '<Badge tone="success">stable</Badge>' },
  { name: "FileTree", purpose: "Display a directory structure.", example: '<FileTree tree={[{ name: "src", type: "folder", children: [{ name: "main.tsx" }] }]} />' },
  { name: "Embed", purpose: "Embed a third-party URL or sandboxed HTML widget.", example: '<Embed src="https://codepen.io/team/codepen/pen/PNaGbb" title="Demo" height={420} />' }
];

// src/lib/mcp-admin/tools/get-mdx-components.ts
var get_mdx_components_default = defineTool8({
  name: "get_mdx_components",
  title: "Get MDX components",
  description: "List the custom MDX components supported by blog posts, with valid examples ready to use in create_post or update_post bodies.",
  inputSchema: {
    name: z7.string().trim().optional().describe("Optional component name to return, such as Chart or Embed.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ name }) => {
    const components = name ? MDX_COMPONENTS.filter((component) => component.name.toLowerCase() === name.toLowerCase()) : MDX_COMPONENTS;
    if (name && components.length === 0) {
      return {
        content: [{ type: "text", text: `Unknown MDX component: ${name}. Call get_mdx_components without a name to list all supported components.` }],
        structuredContent: { components: [], supported: MDX_COMPONENTS.map((component) => component.name) },
        isError: true
      };
    }
    return {
      content: [{ type: "text", text: components.map((component) => `${component.name}: ${component.purpose}
${component.example}`).join("\n\n") }],
      structuredContent: { components }
    };
  }
});

// src/lib/mcp-admin/index.ts
var mcp_admin_default = defineMcp({
  name: "somrit-webcv-admin",
  title: "Somrit Dasgupta \u2014 Site Admin",
  version: "0.5.0",
  instructions: "Owner-only authoring tools for somritdasgupta.in. Connecting requires no login. When an authoring request arrives without an owner_session: retain the full pending request, call authenticate_for_blog_posting exactly once, show the user_code and verification link with a countdown from expires_in, and then poll check_auth_status with the same authorization_request until it returns approved. Pending is normal, not an error; never ask the user to confirm approval and never start a second authentication while the first has time remaining. On approved, immediately resume the preserved action with owner_session. A completed authorization is not a completed publish: never claim a post was published, updated, or deleted unless the mutation tool returns published/updated/deleted: true, verified: true, and a commitSha. Use get_mdx_components before composing rich MDX. Read a post before updating or deleting it and pass expected_sha.",
  tools: [authenticate_for_blog_posting_default, check_auth_status_default, get_mdx_components_default, list_all_posts_default, read_post_source_default, create_post_default, update_post_default, delete_post_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_admin_default, { functionName: "mcp-admin" }));
