// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-author-info.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
var get_author_info_default = defineTool({
  name: "get_author_info",
  title: "Get author info",
  description: "Return public bio and contact links for Somrit Dasgupta (site owner). Use this for 'who is somrit' style questions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Somrit Dasgupta",
      role: "Software Engineer",
      location: "Kolkata, India",
      bio: "Software Engineer building backend systems and AI tools on AWS. Works with LangGraph, AWS Bedrock, and contributes to open source.",
      site: "https://somritdasgupta.in",
      email: "thesomritdasgupta@gmail.com",
      links: {
        github: "https://github.com/somritdasgupta",
        linkedin: "https://www.linkedin.com/in/somritdasgupta",
        x: "https://x.com/kitsomrit"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/tools/list-blog-posts.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
var REPO = "somritdasgupta/webCV";
var DIR = "content/blog";
function parseFrontmatter(src) {
  const m = src.match(/^---\s*\n([\s\S]*?)\n---/);
  if (!m) return {};
  const out = {};
  for (const line of m[1].split("\n")) {
    const kv = line.match(/^(\w+):\s*(.*)$/);
    if (!kv) continue;
    out[kv[1]] = kv[2].replace(/^["']|["']$/g, "").trim();
  }
  return out;
}
var list_blog_posts_default = defineTool2({
  name: "list_blog_posts",
  title: "List blog posts",
  description: "Return published blog posts from somritdasgupta.in with slug, title, date, description, and tags. Drafts and future-dated posts are excluded.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).optional().describe("Maximum number of posts to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const listRes = await fetch(
      `https://api.github.com/repos/${REPO}/contents/${DIR}`,
      { headers: { Accept: "application/vnd.github+json" } }
    );
    if (!listRes.ok) {
      return {
        content: [{ type: "text", text: `GitHub API error: ${listRes.status}` }],
        isError: true
      };
    }
    const files = await listRes.json();
    const mdx = files.filter((f) => f.type === "file" && f.name.endsWith(".mdx"));
    const posts = await Promise.all(
      mdx.map(async (f) => {
        if (!f.download_url) return null;
        const raw = await fetch(f.download_url).then((r) => r.ok ? r.text() : "");
        const fm = parseFrontmatter(raw);
        if (fm.draft === "true") return null;
        const date = fm.date || "";
        if (date && new Date(date).getTime() > Date.now()) return null;
        return {
          slug: f.name.replace(/\.mdx$/, "").toLowerCase(),
          title: fm.title || f.name,
          date,
          description: fm.description || "",
          tags: fm.tags || "",
          url: `https://somritdasgupta.in/blog/${f.name.replace(/\.mdx$/, "").toLowerCase()}`
        };
      })
    );
    const filtered = posts.filter((p) => p !== null).sort((a, b) => (b.date || "").localeCompare(a.date || "")).slice(0, limit ?? 20);
    return {
      content: [{ type: "text", text: JSON.stringify(filtered, null, 2) }],
      structuredContent: { posts: filtered }
    };
  }
});

// src/lib/mcp/tools/get-blog-post.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
var REPO2 = "somritdasgupta/webCV";
var DIR2 = "content/blog";
var get_blog_post_default = defineTool3({
  name: "get_blog_post",
  title: "Get blog post",
  description: "Fetch the full MDX content and frontmatter of a single blog post by its slug (e.g. 'hello-world').",
  inputSchema: {
    slug: z2.string().min(1).describe("Post slug without the .mdx extension, e.g. 'ai-hype'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ slug }) => {
    const safe = slug.replace(/[^a-z0-9-]/gi, "").toLowerCase();
    const url = `https://raw.githubusercontent.com/${REPO2}/main/${DIR2}/${safe}.mdx`;
    const res = await fetch(url);
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `Post not found: ${safe}` }],
        isError: true
      };
    }
    const text = await res.text();
    return {
      content: [{ type: "text", text }],
      structuredContent: {
        slug: safe,
        url: `https://somritdasgupta.in/blog/${safe}`,
        markdown: text
      }
    };
  }
});

// src/lib/mcp/tools/get-github-activity.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z3 } from "npm:zod@^3.25.76";
var USER = "somritdasgupta";
var get_github_activity_default = defineTool4({
  name: "get_github_activity",
  title: "Get GitHub activity",
  description: "Return recent public GitHub activity for somritdasgupta: commits, pull requests, releases, and stars.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max events to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const res = await fetch(
      `https://api.github.com/users/${USER}/events/public?per_page=${limit ?? 20}`,
      { headers: { Accept: "application/vnd.github+json" } }
    );
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `GitHub API error: ${res.status}` }],
        isError: true
      };
    }
    const events = await res.json();
    const summary = events.map((e) => ({
      type: e.type,
      repo: e.repo.name,
      at: e.created_at,
      ref: e.payload.ref,
      commits: e.payload.commits?.map((c) => ({ sha: c.sha.slice(0, 7), message: c.message }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(summary, null, 2) }],
      structuredContent: { events: summary }
    };
  }
});

// src/lib/mcp/tools/get-repos.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z4 } from "npm:zod@^3.25.76";
var USER2 = "somritdasgupta";
var get_repos_default = defineTool5({
  name: "get_repos",
  title: "List public repos",
  description: "Return public GitHub repositories owned by somritdasgupta with name, description, stars, language, and URL.",
  inputSchema: {
    limit: z4.number().int().min(1).max(100).optional().describe("Max repos (default 30).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: true },
  handler: async ({ limit }) => {
    const res = await fetch(
      `https://api.github.com/users/${USER2}/repos?per_page=${limit ?? 30}&sort=updated`,
      { headers: { Accept: "application/vnd.github+json" } }
    );
    if (!res.ok) {
      return {
        content: [{ type: "text", text: `GitHub API error: ${res.status}` }],
        isError: true
      };
    }
    const repos = await res.json();
    const trimmed = repos.filter((r) => !r.fork).map((r) => ({
      name: r.full_name,
      description: r.description,
      url: r.html_url,
      stars: r.stargazers_count,
      language: r.language,
      updated: r.updated_at
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(trimmed, null, 2) }],
      structuredContent: { repos: trimmed }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "somrit-webcv-mcp",
  title: "Somrit Dasgupta \u2014 Personal Site",
  version: "0.1.0",
  instructions: "Tools for exploring Somrit Dasgupta's personal site (somritdasgupta.in): read published blog posts, look up the author's bio and links, and inspect public GitHub activity and repositories. All data is public \u2014 no authentication required.",
  tools: [get_author_info_default, list_blog_posts_default, get_blog_post_default, get_github_activity_default, get_repos_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
